/*
 * TencentBlueKing is pleased to support the open source community by making
 * 蓝鲸智云 - 服务治理 (BlueKing Service Governance) available.
 * Copyright (C) Tencent. All rights reserved.
 * Licensed under the MIT License (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 *  http://opensource.org/licenses/MIT
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * We undertake not to change the open source license (MIT license) applicable
 * to the current version of the project delivered to anyone in the future.
 */

// Package arrangement 定义应用编排相关逻辑
package arrangement

import (
	"context"

	"github.com/pkg/errors"
	"gopkg.in/yaml.v3"

	bkmsapp "github.com/TencentBlueKing/blueking-service-governance/bkms-server/pkg/core/app"
	"github.com/TencentBlueKing/blueking-service-governance/bkms-server/pkg/core/app/appcfg"
	"github.com/TencentBlueKing/blueking-service-governance/bkms-server/pkg/core/render"
)

// 以下常量是编排 values.yaml 时 bkms 命名空间下可用的占位符变量键，
// 即模板中 ${{ bkms.X }} 里的 X。这些变量在编排期（校验、渲染）使用，
// 由部署侧填充具体值后传入渲染器。按业务类别加前缀分组：
// ARTIFACT_（构件/镜像）、APP_（应用）、NETWORKING_（网络）。
const (
	// BkmsArtifactImage is the full image representation
	// e.g. "myapp:1.0.0" or "hub.bktencent.com/blueking/myapp:1.0.0"
	BkmsArtifactImage = "ARTIFACT_IMAGE"
	// BkmsArtifactImageName is image name only (maybe use default registry)
	// e.g. "myapp" or "hub.bktencent.com/blueking/myapp"
	BkmsArtifactImageName = "ARTIFACT_IMAGE_NAME"
	// BkmsArtifactImageTag is image tag only
	// e.g. "1.0.0" or "v20250701"
	BkmsArtifactImageTag = "ARTIFACT_IMAGE_TAG"
	// BkmsArtifactImageRegistry is image registry
	// e.g. "my-registry.com" or "hub.bktencent.com"
	BkmsArtifactImageRegistry = "ARTIFACT_IMAGE_REGISTRY"
	// BkmsArtifactImageRepository is image repository (cannot with registry)
	// e.g. "myapp" or "blueking/myapp"
	BkmsArtifactImageRepository = "ARTIFACT_IMAGE_REPOSITORY"
	// BkmsAppImagePullSecret is the image pull secret name
	// e.g. "my-registry-secret"
	BkmsAppImagePullSecret = "APP_IMAGE_PULL_SECRET" // #nosec G101
	// BkmsNetworkingIngressDomain is the domain generated by the platform and designed
	// for use by the application's Ingress resource, e.g., "app-foobar.example.com"
	BkmsNetworkingIngressDomain = "NETWORKING_INGRESS_DOMAIN"
)

// ArrgType is a type that represents the arrangement type of an application.
type ArrgType string

const (
	// ArrgTypeWorkloadImage "应用源镜像" 编排类型
	ArrgTypeWorkloadImage ArrgType = "workloadImage"
	// ArrgTypeIngressDomain "网络访问 Ingress 域名" 编排类型
	ArrgTypeIngressDomain ArrgType = "ingressDomain"
)

// ValuesArrangeStatus is Values arrangement is a kind of "application arrangement" that is
// performed by defining a custom values.yaml file.
// The arrangement might have different statuses depending on the application.
type ValuesArrangeStatus string

const (
	// ArrgStatusUninitialized indicates that arrange has not been started yet.
	ArrgStatusUninitialized ValuesArrangeStatus = "uninitialized"
	// ArrgStatusConfigured indicates that arrange has been completed.
	ArrgStatusConfigured ValuesArrangeStatus = "configured"
	// ArrgStatusSkipped indicates that arrange has been skipped.
	ArrgStatusSkipped ValuesArrangeStatus = "skipped"
)

// AppArrgStatus is An application's arrangement status, every struct value
// represents an application's arrangement status for a specific arrangement type.
type AppArrgStatus struct {
	// WorkspaceID is the id of the workspace.
	WorkspaceID string `bson:"workspaceID"`
	// AppName is the name of the application.
	AppName string `bson:"appName"`
	// ArrgType is the type of the arrangement.
	ArrgType ArrgType `bson:"arrgType"`
	// Status is the status of the arrangement.
	Status ValuesArrangeStatus `bson:"status"`

	// UpdatedAt is the time when the arrangement was last updated.
	UpdatedAt int64 `bson:"updatedAt"`
}

// PlaceholderVar 是编排 values.yaml 时的可用占位符。
type PlaceholderVar struct {
	// Key 是占位符变量的键，例如 "ARTIFACT_IMAGE"。
	Key string
	// Description 是占位符变量描述。
	Description string
}

// ListPlaceholderVars returns the placeholder variables exposed by the public API.
func ListPlaceholderVars() []PlaceholderVar {
	// TODO: Description 字段国际化
	return []PlaceholderVar{
		{
			Key:         BkmsArtifactImage,
			Description: "镜像地址，如：mirrors.tencent.com/bk/myapp:1.0.0",
		},
		{
			Key:         BkmsArtifactImageName,
			Description: "镜像名，如：mirrors.tencent.com/bk/myapp",
		},
		{
			Key:         BkmsArtifactImageTag,
			Description: "镜像 Tag，如：1.0.0",
		},
		{
			Key:         BkmsArtifactImageRegistry,
			Description: "镜像仓库，如：mirrors.tencent.com",
		},
		{
			Key:         BkmsArtifactImageRepository,
			Description: "镜像库，如：bk/myapp",
		},
		{
			Key:         BkmsAppImagePullSecret,
			Description: "镜像拉取密钥，如：myapp-pull-secret",
		},
	}
}

// AppArranger arranges the application to enable various functionalities.
// This is often achieved by using special placeholders in the values.yaml file.
type AppArranger struct {
	appStore bkmsapp.ApplicationStore
}

// NewAppArranger creates a new WorkloadImageArranger with the given store.
func NewAppArranger(appStore bkmsapp.ApplicationStore) *AppArranger {
	return &AppArranger{
		appStore: appStore,
	}
}

// ArrgResult is a struct that contains the arrangement result of the application,
// it can be also used as the result of validation of the arrangement.
type ArrgResult struct {
	WorkloadImage ArrgResultItem
	IngressDomain ArrgResultItem
}

// ArrgResultItem is a single item for holding the result status for a specific arrangement type.
type ArrgResultItem struct {
	// Status is the status of the arrangement
	Status ValuesArrangeStatus
	// SkippedReason is the reason why the arrangement was skipped, only used when the status is "skipped."
	SkippedReason string
}

// ValidateFileContent validates the given file content based on the file format.
// For YAML format, it validates the values YAML placeholders.
// For TAF format, it returns success directly (TAF format does not require placeholder validation).
//
// - content: the file content
// - format: the file format (yaml or taf)
func (arrg *AppArranger) ValidateFileContent(
	ctx context.Context,
	app *bkmsapp.Application,
	content []byte,
	format appcfg.FileFormat,
) (ArrgResult, error) {
	switch format {
	case appcfg.FileFormatTAF:
		return validateTAFFile(content)
	case appcfg.FileFormatYAML:
		return validateYamlFile(content)
	default:
		return ArrgResult{}, errors.New("invalid file format")
	}
}

// validateYamlFile validates YAML format file content.
// yaml.Unmarshal only checks syntax; variable extraction uses render.ExtractVars
// directly on raw content so both validators share one parse result.
func validateYamlFile(content []byte) (ArrgResult, error) {
	var dummy map[string]any
	if err := yaml.Unmarshal(content, &dummy); err != nil {
		return ArrgResult{}, errors.Wrap(err, "parsing values.yaml")
	}

	vars, err := render.ExtractVars(string(content))
	if err != nil {
		return ArrgResult{}, errors.Wrap(err, "extract placeholder vars from values.yaml")
	}

	errWorkloadImage := validateValuesYamlWorkloadImage(vars)
	// FIXME: 目前该占位符没有实际作用，考虑去掉检查
	errIngressDomain := validateValuesYamlIngressDomain(vars)

	errToItem := func(err error) ArrgResultItem {
		if err != nil {
			return ArrgResultItem{Status: ArrgStatusSkipped, SkippedReason: err.Error()}
		}
		return ArrgResultItem{Status: ArrgStatusConfigured, SkippedReason: ""}
	}

	return ArrgResult{
		WorkloadImage: errToItem(errWorkloadImage),
		IngressDomain: errToItem(errIngressDomain),
	}, nil
}

// validateTAFFile validates TAF format file content.
// TAF format does not require placeholder validation, so it returns success directly.
func validateTAFFile(_ []byte) (ArrgResult, error) {
	return ArrgResult{
		WorkloadImage: ArrgResultItem{Status: ArrgStatusConfigured, SkippedReason: ""},
		IngressDomain: ArrgResultItem{Status: ArrgStatusConfigured, SkippedReason: ""},
	}, nil
}

// Validate the values data to know if it's valid for the workloadImage arrangement.
func validateValuesYamlWorkloadImage(vars render.VarsSet) error {
	bkms := vars[string(render.ContextBkms)]

	// 以下场景三选一均可通过校验
	// image = ${{ bkms.ARTIFACT_IMAGE }}
	// image = ${{ bkms.ARTIFACT_IMAGE_NAME }}:${{ bkms.ARTIFACT_IMAGE_TAG }}
	// image = ${{ bkms.ARTIFACT_IMAGE_REGISTRY }}/${{ bkms.ARTIFACT_IMAGE_REPOSITORY }}:${{ bkms.ARTIFACT_IMAGE_TAG }}
	_, ok := bkms[BkmsArtifactImage]
	if ok {
		return nil
	}
	_, nameOK := bkms[BkmsArtifactImageName]
	_, tagOK := bkms[BkmsArtifactImageTag]
	if nameOK && tagOK {
		return nil
	}
	_, regOK := bkms[BkmsArtifactImageRegistry]
	_, repoOK := bkms[BkmsArtifactImageRepository]
	if regOK && repoOK && tagOK {
		return nil
	}
	return errors.New("missing image placeholders in values.yaml")
}

// Validate the values data to know if it's valid for the ingressDomain arrangement
func validateValuesYamlIngressDomain(vars render.VarsSet) error {
	bkms := vars[string(render.ContextBkms)]
	if _, ok := bkms[BkmsNetworkingIngressDomain]; ok {
		return nil
	}
	return errors.New("missing ingress domain placeholder in values.yaml")
}
