/*
 * TencentBlueKing is pleased to support the open source community by making
 * 蓝鲸智云 - 服务治理 (BlueKing Service Governance) available.
 * Copyright (C) Tencent. All rights reserved.
 * Licensed under the MIT License (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 *  http://opensource.org/licenses/MIT
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * We undertake not to change the open source license (MIT license) applicable
 * to the current version of the project delivered to anyone in the future.
 */

// Package appmodel storage module for the appmodel package, it helps with app model data persistence.
package appmodel

import (
	"context"
	"time"

	"github.com/pkg/errors"
	"go.mongodb.org/mongo-driver/v2/bson"
	"go.mongodb.org/mongo-driver/v2/mongo"
	"go.mongodb.org/mongo-driver/v2/mongo/options"

	"github.com/TencentBlueKing/blueking-service-governance/bkms-server/pkg/common/config"
	"github.com/TencentBlueKing/blueking-service-governance/bkms-server/pkg/common/utils/crypto"
	"github.com/TencentBlueKing/blueking-service-governance/bkms-server/pkg/extension/component"
)

// CollectionName is the name of the MongoDB collection for storing app model data.
const CollectionName = "app_models"

// ErrAppModelNotFound is returned when a app model is not found in the store.
var ErrAppModelNotFound = errors.New("app model not found")

// ErrComponentNotFound is returned when a component is not found in the app model.
var ErrComponentNotFound = errors.New("component not found")

// ErrComponentNameExists is returned when a component name already exists in the app model.
var ErrComponentNameExists = errors.New("component name already exists")

// ErrEnvVarNotFound is returned when an env var is not found in the app model.
var ErrEnvVarNotFound = errors.New("env var not found")

// ErrEnvVarKeyExists is returned when an env var key already exists in the app model.
var ErrEnvVarKeyExists = errors.New("env var key already exists")

// ErrInvalidEnvVarKey is returned when an env var key does not satisfy the Pod env var naming rules.
var ErrInvalidEnvVarKey = errors.New("invalid env var key")

// ErrEnvVarSensitivityImmutable is returned when attempting to change a sensitive env var to non-sensitive.
// Sensitive env vars can only be deleted and recreated, not downgraded.
var ErrEnvVarSensitivityImmutable = errors.New("sensitive env var cannot be changed to non-sensitive")

// ComponentUpdateData 定义了更新 Component 时允许修改的数据
type ComponentUpdateData struct {
	// Name 组件名称
	Name *string
	// Version 组件版本
	Version *string
	// Properties 组件属性
	Properties map[string]any
}

// AppModelStore is the interface for the app model storage.
type AppModelStore interface {
	// CreateAppModel creates a new app model
	CreateAppModel(ctx context.Context, appModel *AppModel) error

	// GetAppModel gets an existing app model by appID
	GetAppModel(ctx context.Context, appID string) (*AppModel, error)

	// UpdateAppModel updates an existing app model
	// if appModel.Components.Name is empty, it will be generated by the system
	UpdateAppModel(ctx context.Context, appModel *AppModel) error

	// DeleteAppModel deletes an app model by appID
	DeleteAppModel(ctx context.Context, appID string) error

	// AddComponent adds a component to an app model atomically using $push.
	// Returns ErrAppModelNotFound if app model not found, ErrComponentNameExists if component name already exists.
	AddComponent(ctx context.Context, appID string, comp *component.Component) error

	// UpdateComponent updates a component in an app model atomically using arrayFilters.
	// Returns ErrAppModelNotFound if app model not found, ErrComponentNotFound if component not found,
	// ErrComponentNameExists if new name conflicts with existing component.
	UpdateComponent(ctx context.Context, appID, compName string, updateData *ComponentUpdateData) error

	// RemoveComponent removes a component from an app model atomically using $pull.
	// Returns ErrAppModelNotFound if app model not found, ErrComponentNotFound if component not found.
	RemoveComponent(ctx context.Context, appID, compName string) error

	// AddAppDefinedEnvVar appends one app-defined env var atomically using $push.
	// Missing CreatedAt and UpdatedAt values are initialized before persistence.
	// Returns ErrAppModelNotFound if app model not found, ErrEnvVarKeyExists if key already exists.
	AddAppDefinedEnvVar(ctx context.Context, appID string, envVar Variable) error

	// UpdateAppDefinedEnvVar updates one app-defined env var atomically by key.
	// Missing UpdatedAt is initialized before persistence. CreatedAt is immutable.
	// Returns ErrAppModelNotFound if app model not found, ErrEnvVarNotFound if env var not found,
	// ErrEnvVarKeyExists if renamed key conflicts with an existing one.
	UpdateAppDefinedEnvVar(ctx context.Context, appID, key string, updated Variable) error

	// RemoveAppDefinedEnvVar removes one app-defined env var atomically by key.
	// Returns ErrAppModelNotFound if app model not found, ErrEnvVarNotFound if env var not found.
	RemoveAppDefinedEnvVar(ctx context.Context, appID, key string) error

	// ListAppDefinedEnvVars lists app-defined env vars stored in workload.envVars.
	ListAppDefinedEnvVars(ctx context.Context, appID string) ([]Variable, error)

	// === Hooks ===
	// SetComponentHooks sets the hooks for component changes
	SetComponentHooks(hooks *ComponentHooks)
}

var _ AppModelStore = &AppModelStoreMongo{}

// ComponentHooks 组件变更时的可选回调，在组件成功添加/移除后自动触发。
// 用于维护 ComponentDef 引用计数等跨集合的副作用。
// 当回调返回 error 时，调用方会将其作为操作错误返回给上层。
type ComponentHooks struct {
	// AfterAdd 在组件成功添加后调用
	AfterAdd func(ctx context.Context, comps []*component.Component) error
	// AfterRemove 在组件成功移除后调用（RemoveComponent 和 DeleteAppModel 共用）
	AfterRemove func(ctx context.Context, comps []*component.Component) error
}

// AppModelStoreMongo is the implementation of AppModelStore using MongoDB.
type AppModelStoreMongo struct {
	// Collection is the MongoDB collection for storing app model data.
	collection     *mongo.Collection
	componentHooks *ComponentHooks
}

// SetComponentHooks 设置组件变更的回调函数
func (s *AppModelStoreMongo) SetComponentHooks(hooks *ComponentHooks) {
	s.componentHooks = hooks
}

// NewAppModelStoreMongo creates a new AppModelStore, it accepts a MongoDB client and database name.
func NewAppModelStoreMongo(client *mongo.Client, dbName string) (*AppModelStoreMongo, error) {
	coll := client.Database(dbName).Collection(CollectionName)
	// 索引（由 golang-migrate 维护）：
	// - 唯一：appID
	return &AppModelStoreMongo{collection: coll}, nil
}

// CreateAppModel creates a new app model
//
// - ctx: The context object for cancellation and timeout
// - appModel: The app model to create
//
// Return an error if the operation fails.
func (s *AppModelStoreMongo) CreateAppModel(ctx context.Context, appModel *AppModel) error {
	appModel.EnsureComponentsName()
	now := time.Now()
	for i := range appModel.Workload.EnvVars {
		appModel.Workload.EnvVars[i].CreatedAt = now
		appModel.Workload.EnvVars[i].UpdatedAt = now
	}

	// Validate the app model struct to ensure required fields are present
	if err := validate.Struct(appModel); err != nil {
		return errors.Wrap(formatValidationError(err), "app model validation failed")
	}

	// Encrypt sensitive app-defined env vars before persisting.
	if err := encryptSensitiveEnvVars(appModel.Workload.EnvVars); err != nil {
		return errors.Wrap(err, "encrypt app model env vars")
	}

	_, err := s.collection.InsertOne(ctx, appModel)
	if err != nil {
		// Check if it's a duplicate key error
		if mongo.IsDuplicateKeyError(err) {
			return errors.New("app model with the same appID already exists")
		}
		return err
	}
	return nil
}

// GetAppModel gets an app model by appID
//
// - ctx: The context object for cancellation and timeout
// - appID: The ID of the app
//
// Return an error if the operation fails, ErrAppModelNotFound if the app model is not found.
func (s *AppModelStoreMongo) GetAppModel(ctx context.Context, appID string) (*AppModel, error) {
	appModel := new(AppModel)
	err := s.collection.FindOne(ctx, bson.M{"appID": appID}).Decode(appModel)
	if err != nil {
		if errors.Is(err, mongo.ErrNoDocuments) {
			// When no record can be found, return a new error
			return nil, ErrAppModelNotFound
		}
		return nil, err
	}

	appModel.NormalizeComponents()
	// Decrypt sensitive app-defined env vars so all callers (e.g. deployment,
	// serializers) see the plaintext value.
	decryptSensitiveEnvVars(appModel.Workload.EnvVars)

	return appModel, nil
}

// UpdateAppModel updates an app model
//
// - ctx: The context object for cancellation and timeout
// - appModel: The app model to update
//
// Return an error if the operation fails, ErrAppModelNotFound if the app model is not found.
func (s *AppModelStoreMongo) UpdateAppModel(ctx context.Context, appModel *AppModel) error {
	appModel.EnsureComponentsName()

	// Validate the app model struct to ensure required fields are present
	if err := validate.Struct(appModel); err != nil {
		return errors.Wrap(formatValidationError(err), "app model validation failed")
	}

	// Encrypt sensitive app-defined env vars before persisting.
	if err := encryptSensitiveEnvVars(appModel.Workload.EnvVars); err != nil {
		return errors.Wrap(err, "encrypt app model env vars")
	}

	result, err := s.collection.ReplaceOne(ctx, bson.M{"appID": appModel.AppID}, appModel)
	if err != nil {
		return errors.Wrap(err, "update app model")
	}
	if result.MatchedCount == 0 {
		return ErrAppModelNotFound
	}
	return nil
}

// DeleteAppModel deletes an app model by appID
//
// - ctx: The context object for cancellation and timeout
// - appID: The ID of the app
//
// Return an error if the operation fails, ErrAppModelNotFound if the app model is not found.
func (s *AppModelStoreMongo) DeleteAppModel(ctx context.Context, appID string) error {
	// 如果设置了 Hook，先查出所有组件信息
	var comps []*component.Component
	if s.componentHooks != nil && s.componentHooks.AfterRemove != nil {
		appModel, err := s.GetAppModel(ctx, appID)
		if err != nil {
			if errors.Is(err, ErrAppModelNotFound) {
				return ErrAppModelNotFound
			}
			return errors.Wrap(err, "get app model for component hook")
		}
		comps = appModel.Components
	}

	result, err := s.collection.DeleteOne(ctx, bson.M{"appID": appID})
	if err != nil {
		return errors.Wrapf(err, "delete app model for appID [%s]", appID)
	}
	if result.DeletedCount == 0 {
		return ErrAppModelNotFound
	}

	// 成功后触发 Hook
	if len(comps) > 0 {
		if err := s.componentHooks.AfterRemove(ctx, comps); err != nil {
			return errors.Wrap(err, "component hook after delete app model")
		}
	}
	return nil
}

// AddComponent adds a component to an app model atomically using $push.
//
// - ctx: The context object for cancellation and timeout
// - appID: The ID of the app
// - comp: The component to add
//
// Returns ErrAppModelNotFound if app model not found, ErrComponentNameExists if component name already exists.
func (s *AppModelStoreMongo) AddComponent(ctx context.Context, appID string, comp *component.Component) error {
	// Ensure the component has a name
	comp.EnsureName()

	// Use filter to check app model exists and component name does not exist
	filter := bson.M{
		"appID": appID,
		"components": bson.M{
			"$not": bson.M{
				"$elemMatch": bson.M{
					"name": comp.Name,
				},
			},
		},
	}

	update := bson.M{
		"$push": bson.M{
			"components": comp,
		},
	}

	result, err := s.collection.UpdateOne(ctx, filter, update)
	if err != nil {
		return errors.Wrap(err, "add component to app model")
	}

	if result.MatchedCount == 0 {
		// Check if app model exists
		exists, checkErr := s.appModelExists(ctx, appID)
		if checkErr != nil {
			return errors.Wrap(checkErr, "check app model exists")
		}
		if !exists {
			return ErrAppModelNotFound
		}
		return ErrComponentNameExists
	}

	// 成功后触发 Hook
	if s.componentHooks != nil && s.componentHooks.AfterAdd != nil {
		if err := s.componentHooks.AfterAdd(ctx, []*component.Component{comp}); err != nil {
			return errors.Wrap(err, "component hook after add")
		}
	}
	return nil
}

// UpdateComponent updates a component in an app model atomically using arrayFilters.
//
// - ctx: The context object for cancellation and timeout
// - appID: The ID of the app
// - compName: The name of the component to update
// - updateData: The data to update
//
// Returns ErrAppModelNotFound if app model not found, ErrComponentNotFound if component not found,
// ErrComponentNameExists if new name conflicts with existing component.
func (s *AppModelStoreMongo) UpdateComponent(
	ctx context.Context,
	appID, compName string,
	updateData *ComponentUpdateData,
) error {
	if updateData == nil {
		return nil
	}

	filter := bson.M{"appID": appID}
	updateSet := bson.M{}
	needUpdate := false

	// Handle name update with uniqueness check
	if updateData.Name != nil && *updateData.Name != "" && *updateData.Name != compName {
		// Check that no other component has the new name
		filter["$nor"] = []bson.M{
			{
				"components": bson.M{
					"$elemMatch": bson.M{
						"name": *updateData.Name,
					},
				},
			},
		}
		updateSet["components.$[elem].name"] = *updateData.Name
		needUpdate = true
	}

	if updateData.Version != nil {
		updateSet["components.$[elem].version"] = *updateData.Version
		needUpdate = true
	}

	if updateData.Properties != nil {
		updateSet["components.$[elem].properties"] = updateData.Properties
		needUpdate = true
	}

	if !needUpdate {
		return nil
	}

	update := bson.M{"$set": updateSet}

	opts := options.UpdateOne().SetArrayFilters([]any{
		bson.M{"elem.name": compName},
	})

	result, err := s.collection.UpdateOne(ctx, filter, update, opts)
	if err != nil {
		return errors.Wrap(err, "update component in app model")
	}

	if result.MatchedCount == 0 {
		// Check if app model exists
		exists, checkErr := s.appModelExists(ctx, appID)
		if checkErr != nil {
			return errors.Wrap(checkErr, "check app model exists")
		}
		if !exists {
			return ErrAppModelNotFound
		}
		// If name update was requested, it might be a name conflict
		if updateData.Name != nil && *updateData.Name != "" && *updateData.Name != compName {
			return ErrComponentNameExists
		}
		return ErrComponentNotFound
	}

	return nil
}

// RemoveComponent removes a component from an app model atomically using $pull.
//
// - ctx: The context object for cancellation and timeout
// - appID: The ID of the app
// - compName: The name of the component to remove
//
// Returns ErrAppModelNotFound if app model not found, ErrComponentNotFound if component not found.
func (s *AppModelStoreMongo) RemoveComponent(ctx context.Context, appID, compName string) error {
	// 如果设置了 Hook，需要先查出被删除的组件信息
	var removedComp *component.Component
	if s.componentHooks != nil && s.componentHooks.AfterRemove != nil {
		appModel, err := s.GetAppModel(ctx, appID)
		if err != nil {
			if errors.Is(err, ErrAppModelNotFound) {
				return ErrAppModelNotFound
			}
			return errors.Wrap(err, "get app model for component hook")
		}
		for i := range appModel.Components {
			if appModel.Components[i].Name == compName {
				removedComp = appModel.Components[i]
				break
			}
		}
	}

	filter := bson.M{"appID": appID}

	update := bson.M{
		"$pull": bson.M{
			"components": bson.M{"name": compName},
		},
	}

	result, err := s.collection.UpdateOne(ctx, filter, update)
	if err != nil {
		return errors.Wrap(err, "remove component from app model")
	}

	if result.MatchedCount == 0 {
		return ErrAppModelNotFound
	}

	if result.ModifiedCount == 0 {
		return ErrComponentNotFound
	}

	// 成功后触发 Hook
	if removedComp != nil {
		if err := s.componentHooks.AfterRemove(ctx, []*component.Component{removedComp}); err != nil {
			return errors.Wrap(err, "component hook after remove")
		}
	}
	return nil
}

// AddAppDefinedEnvVar appends one app-defined env var atomically using $push.
func (s *AppModelStoreMongo) AddAppDefinedEnvVar(ctx context.Context, appID string, envVar Variable) error {
	if envVar.CreatedAt.IsZero() {
		envVar.CreatedAt = time.Now()
	}
	if envVar.UpdatedAt.IsZero() {
		envVar.UpdatedAt = envVar.CreatedAt
	}

	stored := envVar
	if envVar.IsSensitive {
		encrypted, err := crypto.AESEncrypt(config.G.Encrypt.Secret, envVar.Value)
		if err != nil {
			return errors.Wrapf(err, "encrypt env var %s", envVar.Key)
		}
		stored.Value = encrypted
	}

	filter := bson.M{
		"appID": appID,
		"workload.envVars": bson.M{
			"$not": bson.M{
				"$elemMatch": bson.M{"key": envVar.Key},
			},
		},
	}
	update := bson.M{
		"$push": bson.M{
			"workload.envVars": stored,
		},
	}

	result, err := s.collection.UpdateOne(ctx, filter, update)
	if err != nil {
		return errors.Wrap(err, "add app defined env var")
	}
	if result.MatchedCount == 0 {
		exists, checkErr := s.appModelExists(ctx, appID)
		if checkErr != nil {
			return errors.Wrap(checkErr, "check app model exists")
		}
		if !exists {
			return ErrAppModelNotFound
		}
		return ErrEnvVarKeyExists
	}
	return nil
}

// UpdateAppDefinedEnvVar updates one app-defined env var atomically by key.
func (s *AppModelStoreMongo) UpdateAppDefinedEnvVar(ctx context.Context, appID, key string, updated Variable) error {
	if updated.UpdatedAt.IsZero() {
		updated.UpdatedAt = time.Now()
	}

	filter := bson.M{
		"appID":                appID,
		"workload.envVars.key": key,
	}
	if updated.Key != key {
		filter["$nor"] = []bson.M{
			{
				"workload.envVars": bson.M{
					"$elemMatch": bson.M{"key": updated.Key},
				},
			},
		}
	}

	value := updated.Value
	if updated.IsSensitive {
		encrypted, err := crypto.AESEncrypt(config.G.Encrypt.Secret, updated.Value)
		if err != nil {
			return errors.Wrapf(err, "encrypt env var %s", updated.Key)
		}
		value = encrypted
	}

	// CreatedAt is immutable and intentionally omitted from $set.
	update := bson.M{
		"$set": bson.M{
			"workload.envVars.$[elem].key":         updated.Key,
			"workload.envVars.$[elem].value":       value,
			"workload.envVars.$[elem].description": updated.Description,
			"workload.envVars.$[elem].isSensitive": updated.IsSensitive,
			"workload.envVars.$[elem].updatedAt":   updated.UpdatedAt,
		},
	}
	opts := options.UpdateOne().SetArrayFilters([]any{
		bson.M{"elem.key": key},
	})

	result, err := s.collection.UpdateOne(ctx, filter, update, opts)
	if err != nil {
		return errors.Wrap(err, "update app defined env var")
	}
	if result.MatchedCount == 0 {
		exists, checkErr := s.appModelExists(ctx, appID)
		if checkErr != nil {
			return errors.Wrap(checkErr, "check app model exists")
		}
		if !exists {
			return ErrAppModelNotFound
		}

		oldKeyExists, checkErr := s.appDefinedEnvVarExists(ctx, appID, key)
		if checkErr != nil {
			return errors.Wrap(checkErr, "check app defined env var exists")
		}
		if !oldKeyExists {
			return ErrEnvVarNotFound
		}
		return ErrEnvVarKeyExists
	}
	return nil
}

// RemoveAppDefinedEnvVar removes one app-defined env var atomically by key.
func (s *AppModelStoreMongo) RemoveAppDefinedEnvVar(ctx context.Context, appID, key string) error {
	filter := bson.M{
		"appID":                appID,
		"workload.envVars.key": key,
	}
	update := bson.M{
		"$pull": bson.M{
			"workload.envVars": bson.M{"key": key},
		},
	}

	result, err := s.collection.UpdateOne(ctx, filter, update)
	if err != nil {
		return errors.Wrap(err, "remove app defined env var")
	}
	if result.MatchedCount == 0 {
		exists, checkErr := s.appModelExists(ctx, appID)
		if checkErr != nil {
			return errors.Wrap(checkErr, "check app model exists")
		}
		if !exists {
			return ErrAppModelNotFound
		}
		return ErrEnvVarNotFound
	}
	return nil
}

// ListAppDefinedEnvVars lists app-defined env vars stored in workload.envVars.
func (s *AppModelStoreMongo) ListAppDefinedEnvVars(ctx context.Context, appID string) ([]Variable, error) {
	result := struct {
		Workload struct {
			EnvVars []Variable `bson:"envVars,omitempty"`
		} `bson:"workload"`
	}{}
	err := s.collection.FindOne(
		ctx,
		bson.M{"appID": appID},
		options.FindOne().SetProjection(bson.M{
			"_id":              0,
			"workload.envVars": 1,
		}),
	).Decode(&result)
	if err != nil {
		if errors.Is(err, mongo.ErrNoDocuments) {
			return nil, ErrAppModelNotFound
		}
		return nil, err
	}
	decryptSensitiveEnvVars(result.Workload.EnvVars)
	return result.Workload.EnvVars, nil
}

// appModelExists checks if an app model exists by appID.
func (s *AppModelStoreMongo) appModelExists(ctx context.Context, appID string) (bool, error) {
	count, err := s.collection.CountDocuments(ctx, bson.M{"appID": appID}, options.Count().SetLimit(1))
	if err != nil {
		return false, err
	}
	return count > 0, nil
}

func (s *AppModelStoreMongo) appDefinedEnvVarExists(ctx context.Context, appID, key string) (bool, error) {
	count, err := s.collection.CountDocuments(
		ctx,
		bson.M{
			"appID":                appID,
			"workload.envVars.key": key,
		},
		options.Count().SetLimit(1),
	)
	if err != nil {
		return false, err
	}
	return count > 0, nil
}

// encryptSensitiveEnvVars encrypts the values of sensitive app-defined env vars in
// place. Non-sensitive vars are left as plaintext on purpose so the bulk of existing
// data does not need to be migrated.
func encryptSensitiveEnvVars(vars []Variable) error {
	for i := range vars {
		if !vars[i].IsSensitive {
			continue
		}
		encrypted, err := crypto.AESEncrypt(config.G.Encrypt.Secret, vars[i].Value)
		if err != nil {
			return errors.Wrapf(err, "encrypt env var %s", vars[i].Key)
		}
		vars[i].Value = encrypted
	}
	return nil
}

// decryptSensitiveEnvVars decrypts the values of sensitive app-defined env vars in
// place. For backward compatibility with sensitive vars that were previously stored
// as plaintext, a decryption failure leaves the original value unchanged, so no data
// migration is required.
func decryptSensitiveEnvVars(vars []Variable) {
	for i := range vars {
		if !vars[i].IsSensitive {
			continue
		}
		decrypted, err := crypto.AESDecrypt(config.G.Encrypt.Secret, vars[i].Value)
		if err != nil {
			continue
		}
		vars[i].Value = decrypted
	}
}
