/*
 * TencentBlueKing is pleased to support the open source community by making
 * 蓝鲸智云 - 服务治理 (BlueKing Service Governance) available.
 * Copyright (C) Tencent. All rights reserved.
 * Licensed under the MIT License (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 *  http://opensource.org/licenses/MIT
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * We undertake not to change the open source license (MIT license) applicable
 * to the current version of the project delivered to anyone in the future.
 */

// Package plugin 定义了基于应用模型的 workload 插件扩展机制，目前支持按照应用类型扩展不同的
// workload 行为，比如 tRPC 类型的应用会注入额外的 volume 挂载和创建额外的 ConfigMap 文件
package plugin

import (
	"context"
	"sync"

	"github.com/pkg/errors"
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	"k8s.io/apimachinery/pkg/runtime"

	bkmsapp "github.com/TencentBlueKing/blueking-service-governance/bkms-server/pkg/core/app"
	envmodel "github.com/TencentBlueKing/blueking-service-governance/bkms-server/pkg/core/env/model"
	"github.com/TencentBlueKing/blueking-service-governance/bkms-server/pkg/workload/appmodelcore/appmodel"
	"github.com/TencentBlueKing/blueking-service-governance/bkms-server/pkg/workload/appmodelcore/envvarrefs"
)

// RenderContext shares env vars and undefined-reference collection across renderers in one build.
type RenderContext struct {
	EnvVars   map[string]string
	Collector *envvarrefs.Collector
}

// WorkloadPlugin defines extension points for workload types.
type WorkloadPlugin interface {
	// Type returns the workload type handled by this plugin.
	Type() string

	// Start initializes a plugin session for this build.
	// A session can do some initialization work and cache results for later use.
	Start(
		ctx context.Context,
		env *envmodel.Environment,
		app *bkmsapp.Application,
		appModel *appmodel.AppModel,
		renderCtx RenderContext,
	) (WorkloadPluginSession, error)
}

// WorkloadPluginSession provides extension results for the workload build.
type WorkloadPluginSession interface {
	// Storage returns extra volume mounts and volumes, they will be injected into the workload pod spec.
	Storage(ctx context.Context) ([]corev1.VolumeMount, []corev1.Volume, error)

	// ExtraResources returns extra objects generated by the plugin, they will be created together with the workload.
	ExtraResources(ctx context.Context) ([]unstructured.Unstructured, error)

	// InitContainers returns init containers to be injected into the workload pod spec.
	// Init containers run before the main containers and can be used for tasks like
	// runtime config rendering (e.g., envsubst for Downward API variables).
	InitContainers(ctx context.Context) ([]corev1.Container, error)
}

// The registry type to hold registered workload plugins.
type workloadPluginRegistry struct {
	mu sync.RWMutex

	// {appType: WorkloadPlugin}
	plugins map[string]WorkloadPlugin
}

// The global registry of workload plugins.
var workloadPlugins = &workloadPluginRegistry{
	plugins: map[string]WorkloadPlugin{},
}

// RegisterWorkloadPlugin registers a workload plugin by its type.
func RegisterWorkloadPlugin(plugin WorkloadPlugin) error {
	workloadType := plugin.Type()
	if workloadType == "" {
		return errors.New("workload plugin type is empty")
	}

	workloadPlugins.mu.Lock()
	defer workloadPlugins.mu.Unlock()
	if _, exists := workloadPlugins.plugins[workloadType]; exists {
		return errors.Errorf("workload plugin %q already registered", workloadType)
	}
	workloadPlugins.plugins[workloadType] = plugin
	return nil
}

// MustRegisterWorkloadPlugin registers a plugin or panics on error.
func MustRegisterWorkloadPlugin(plugin WorkloadPlugin) {
	if err := RegisterWorkloadPlugin(plugin); err != nil {
		panic(err)
	}
}

// GetWorkloadPlugin retrieves a registered workload plugin by its type.
// Args:
//   - workloadType: the workload type string.
func GetWorkloadPlugin(workloadType string) (WorkloadPlugin, error) {
	// Default to trpc plugin for backward compatibility.
	if workloadType == "" {
		workloadType = appmodel.WorkloadTypeTrpc
	}

	workloadPlugins.mu.RLock()
	defer workloadPlugins.mu.RUnlock()
	plugin, ok := workloadPlugins.plugins[workloadType]
	if !ok {
		return nil, errors.Errorf("unsupported workload type %q", workloadType)
	}
	return plugin, nil
}

// ToUnstructured is a helper function to convert runtime.Objects to unstructured.Unstructured objects.
func ToUnstructured(inputObjs ...runtime.Object) ([]unstructured.Unstructured, error) {
	var items []unstructured.Unstructured
	for _, input := range inputObjs {
		obj, err := runtime.DefaultUnstructuredConverter.ToUnstructured(input)
		if err != nil {
			return nil, errors.Wrap(err, "converting object to unstructured")
		}
		items = append(items, unstructured.Unstructured{Object: obj})
	}
	return items, nil
}
