package updater

import (
	"context"
	"fmt"
	"io"
	"net/http"
	"regexp"
	"runtime"

	selfupdate "github.com/creativeprojects/go-selfupdate"
)

const (
	// GitHub builds always update from the official open-source repository.
	githubRepository = "TencentBlueKing/blueking-service-governance"
	// checksumFilename is generated by GoReleaser and published beside the binaries.
	checksumFilename = "checksums.txt"
)

// githubProvider delegates release discovery, download, checksum validation,
// and executable replacement to go-selfupdate.
type githubProvider struct {
	updater    *selfupdate.Updater
	repository selfupdate.Repository
}

// newGitHubProvider restricts discovery to the exact bkms-cli platform asset
// and requires the shared GoReleaser checksum file before an update can run.
func newGitHubProvider() (*githubProvider, error) {
	slug := selfupdate.ParseSlug(githubRepository)
	config, err := githubUpdaterConfig()
	if err != nil {
		return nil, err
	}

	instance, err := selfupdate.NewUpdater(config)
	if err != nil {
		return nil, fmt.Errorf("create GitHub updater: %w", err)
	}

	return &githubProvider{updater: instance, repository: slug}, nil
}

// githubUpdaterConfig defines the GitHub release asset and checksum contract.
func githubUpdaterConfig() (selfupdate.Config, error) {
	assetName, err := platformAssetName(runtime.GOOS, runtime.GOARCH)
	if err != nil {
		return selfupdate.Config{}, err
	}
	source, err := selfupdate.NewGitHubSource(selfupdate.GitHubConfig{})
	if err != nil {
		return selfupdate.Config{}, fmt.Errorf("create GitHub source: %w", err)
	}

	return selfupdate.Config{
		Source:    maxBytesSource{Source: source, limit: maxBinarySize},
		Validator: &selfupdate.ChecksumValidator{UniqueFilename: checksumFilename},
		Filters:   []string{"^" + regexp.QuoteMeta(assetName) + "$"},
	}, nil
}

// maxBytesSource limits every downloaded release asset before go-selfupdate
// reads it into memory.
type maxBytesSource struct {
	selfupdate.Source
	limit int64
}

func (s maxBytesSource) DownloadReleaseAsset(
	ctx context.Context,
	release *selfupdate.Release,
	assetID int64,
) (io.ReadCloser, error) {
	body, err := s.Source.DownloadReleaseAsset(ctx, release, assetID)
	if err != nil {
		return nil, err
	}
	// GitHubSource returns a streaming response body, so this limit applies
	// before go-selfupdate reads the asset into memory.
	return http.MaxBytesReader(nil, body, s.limit), nil
}

// Check discovers the latest compatible release without downloading its binary.
func (p *githubProvider) Check(ctx context.Context, current string) (Info, error) {
	info, _, err := p.detect(ctx, current)
	return info, err
}

// Update installs the latest compatible release when its SemVer is newer.
func (p *githubProvider) Update(ctx context.Context, current string) (Info, error) {
	info, release, err := p.detect(ctx, current)
	if err != nil || !info.Available {
		return info, err
	}
	if err = validateBinarySize(int64(release.AssetByteSize)); err != nil {
		return info, fmt.Errorf("validate GitHub release size: %w", err)
	}

	executable, err := selfupdate.ExecutablePath()
	if err != nil {
		return info, fmt.Errorf("locate executable: %w", err)
	}
	if err := p.updater.UpdateTo(ctx, release, executable); err != nil {
		return info, fmt.Errorf("apply GitHub update: %w", normalizeBinarySizeError(err))
	}
	return info, nil
}

// detect keeps release selection shared by Check and Update. The returned
// release contains the binary and checksum assets selected by go-selfupdate.
func (p *githubProvider) detect(ctx context.Context, current string) (Info, *selfupdate.Release, error) {
	currentVersion, err := parseVersion(current)
	if err != nil {
		return Info{}, nil, fmt.Errorf("parse current version: %w", err)
	}

	release, found, err := p.updater.DetectLatest(ctx, p.repository)
	if err != nil {
		return Info{}, nil, fmt.Errorf("detect latest GitHub release: %w", err)
	}
	if !found {
		return Info{}, nil, ErrNoRelease
	}

	latestVersion, err := parseVersion(release.Version())
	if err != nil {
		return Info{}, nil, fmt.Errorf("parse latest GitHub version: %w", err)
	}
	return buildInfo(currentVersion, latestVersion), release, nil
}
