name: VolumeConfigMap
version: v1.0.0
description: 将 data 内容以 configmap 的形式挂载到应用中
scopeType: global
isBuiltin: true
properties:
- name: configName
  type: STRING
  defaultValue: configmap
  description: configmap名称
- name: data
  type: TEXT
  defaultValue: data
  description: configmap内容
- name: path
  type: STRING
  defaultValue: /data
  description: 挂载路径
patchers:
- |-
  spec:
    template:
      spec:
        volumes:
          - name: "{{ .name }}"
            configMap:
              name: "{{ .name }}"
              items:
              - key: "{{ .name }}"
                path: "{{ .name }}"
        containers:
          - name: "{{ .bkmsContainerName }}"
            volumeMounts:
            - name: "{{ .name }}"
              mountPath: "{{ .path }}"
              subPath: "{{.name}}"
specs:
- |-
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: "{{ .name }}"
  data:
    "{{ .name }}": {{ printf "%q" (or .data "") }}
