// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"io"

	mock "github.com/stretchr/testify/mock"

	"github.com/TencentBlueKing/blueking-service-governance/bkms-cli/pkg/client"
)

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// BatchUpdateInstance provides a mock function for the type MockClient
func (_mock *MockClient) BatchUpdateInstance(ctx context.Context, appID string, envName string, imageTag string, updateStrategy string) error {
	ret := _mock.Called(ctx, appID, envName, imageTag, updateStrategy)

	if len(ret) == 0 {
		panic("no return value specified for BatchUpdateInstance")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) error); ok {
		r0 = returnFunc(ctx, appID, envName, imageTag, updateStrategy)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_BatchUpdateInstance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BatchUpdateInstance'
type MockClient_BatchUpdateInstance_Call struct {
	*mock.Call
}

// BatchUpdateInstance is a helper method to define mock.On call
//   - ctx context.Context
//   - appID string
//   - envName string
//   - imageTag string
//   - updateStrategy string
func (_e *MockClient_Expecter) BatchUpdateInstance(ctx any, appID any, envName any, imageTag any, updateStrategy any) *MockClient_BatchUpdateInstance_Call {
	return &MockClient_BatchUpdateInstance_Call{Call: _e.mock.On("BatchUpdateInstance", ctx, appID, envName, imageTag, updateStrategy)}
}

func (_c *MockClient_BatchUpdateInstance_Call) Run(run func(ctx context.Context, appID string, envName string, imageTag string, updateStrategy string)) *MockClient_BatchUpdateInstance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockClient_BatchUpdateInstance_Call) Return(err error) *MockClient_BatchUpdateInstance_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_BatchUpdateInstance_Call) RunAndReturn(run func(ctx context.Context, appID string, envName string, imageTag string, updateStrategy string) error) *MockClient_BatchUpdateInstance_Call {
	_c.Call.Return(run)
	return _c
}

// CreateApp provides a mock function for the type MockClient
func (_mock *MockClient) CreateApp(ctx context.Context, workspaceID string, body any) (*client.AppMinimal, error) {
	ret := _mock.Called(ctx, workspaceID, body)

	if len(ret) == 0 {
		panic("no return value specified for CreateApp")
	}

	var r0 *client.AppMinimal
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, any) (*client.AppMinimal, error)); ok {
		return returnFunc(ctx, workspaceID, body)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, any) *client.AppMinimal); ok {
		r0 = returnFunc(ctx, workspaceID, body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.AppMinimal)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, any) error); ok {
		r1 = returnFunc(ctx, workspaceID, body)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_CreateApp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateApp'
type MockClient_CreateApp_Call struct {
	*mock.Call
}

// CreateApp is a helper method to define mock.On call
//   - ctx context.Context
//   - workspaceID string
//   - body any
func (_e *MockClient_Expecter) CreateApp(ctx any, workspaceID any, body any) *MockClient_CreateApp_Call {
	return &MockClient_CreateApp_Call{Call: _e.mock.On("CreateApp", ctx, workspaceID, body)}
}

func (_c *MockClient_CreateApp_Call) Run(run func(ctx context.Context, workspaceID string, body any)) *MockClient_CreateApp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_CreateApp_Call) Return(appMinimal *client.AppMinimal, err error) *MockClient_CreateApp_Call {
	_c.Call.Return(appMinimal, err)
	return _c
}

func (_c *MockClient_CreateApp_Call) RunAndReturn(run func(ctx context.Context, workspaceID string, body any) (*client.AppMinimal, error)) *MockClient_CreateApp_Call {
	_c.Call.Return(run)
	return _c
}

// CreateAppBuild provides a mock function for the type MockClient
func (_mock *MockClient) CreateAppBuild(ctx context.Context, appID string, opts client.BuildOptions) error {
	ret := _mock.Called(ctx, appID, opts)

	if len(ret) == 0 {
		panic("no return value specified for CreateAppBuild")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, client.BuildOptions) error); ok {
		r0 = returnFunc(ctx, appID, opts)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_CreateAppBuild_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAppBuild'
type MockClient_CreateAppBuild_Call struct {
	*mock.Call
}

// CreateAppBuild is a helper method to define mock.On call
//   - ctx context.Context
//   - appID string
//   - opts client.BuildOptions
func (_e *MockClient_Expecter) CreateAppBuild(ctx any, appID any, opts any) *MockClient_CreateAppBuild_Call {
	return &MockClient_CreateAppBuild_Call{Call: _e.mock.On("CreateAppBuild", ctx, appID, opts)}
}

func (_c *MockClient_CreateAppBuild_Call) Run(run func(ctx context.Context, appID string, opts client.BuildOptions)) *MockClient_CreateAppBuild_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 client.BuildOptions
		if args[2] != nil {
			arg2 = args[2].(client.BuildOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_CreateAppBuild_Call) Return(err error) *MockClient_CreateAppBuild_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_CreateAppBuild_Call) RunAndReturn(run func(ctx context.Context, appID string, opts client.BuildOptions) error) *MockClient_CreateAppBuild_Call {
	_c.Call.Return(run)
	return _c
}

// CreateAppHelmDeploy provides a mock function for the type MockClient
func (_mock *MockClient) CreateAppHelmDeploy(ctx context.Context, appID string, envName string, opts client.HelmDeployOptions) error {
	ret := _mock.Called(ctx, appID, envName, opts)

	if len(ret) == 0 {
		panic("no return value specified for CreateAppHelmDeploy")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, client.HelmDeployOptions) error); ok {
		r0 = returnFunc(ctx, appID, envName, opts)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_CreateAppHelmDeploy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAppHelmDeploy'
type MockClient_CreateAppHelmDeploy_Call struct {
	*mock.Call
}

// CreateAppHelmDeploy is a helper method to define mock.On call
//   - ctx context.Context
//   - appID string
//   - envName string
//   - opts client.HelmDeployOptions
func (_e *MockClient_Expecter) CreateAppHelmDeploy(ctx any, appID any, envName any, opts any) *MockClient_CreateAppHelmDeploy_Call {
	return &MockClient_CreateAppHelmDeploy_Call{Call: _e.mock.On("CreateAppHelmDeploy", ctx, appID, envName, opts)}
}

func (_c *MockClient_CreateAppHelmDeploy_Call) Run(run func(ctx context.Context, appID string, envName string, opts client.HelmDeployOptions)) *MockClient_CreateAppHelmDeploy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 client.HelmDeployOptions
		if args[3] != nil {
			arg3 = args[3].(client.HelmDeployOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockClient_CreateAppHelmDeploy_Call) Return(err error) *MockClient_CreateAppHelmDeploy_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_CreateAppHelmDeploy_Call) RunAndReturn(run func(ctx context.Context, appID string, envName string, opts client.HelmDeployOptions) error) *MockClient_CreateAppHelmDeploy_Call {
	_c.Call.Return(run)
	return _c
}

// CreateAppTafDeploy provides a mock function for the type MockClient
func (_mock *MockClient) CreateAppTafDeploy(ctx context.Context, appID string, envName string, opts client.AppModelDeployOptions) error {
	ret := _mock.Called(ctx, appID, envName, opts)

	if len(ret) == 0 {
		panic("no return value specified for CreateAppTafDeploy")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, client.AppModelDeployOptions) error); ok {
		r0 = returnFunc(ctx, appID, envName, opts)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_CreateAppTafDeploy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAppTafDeploy'
type MockClient_CreateAppTafDeploy_Call struct {
	*mock.Call
}

// CreateAppTafDeploy is a helper method to define mock.On call
//   - ctx context.Context
//   - appID string
//   - envName string
//   - opts client.AppModelDeployOptions
func (_e *MockClient_Expecter) CreateAppTafDeploy(ctx any, appID any, envName any, opts any) *MockClient_CreateAppTafDeploy_Call {
	return &MockClient_CreateAppTafDeploy_Call{Call: _e.mock.On("CreateAppTafDeploy", ctx, appID, envName, opts)}
}

func (_c *MockClient_CreateAppTafDeploy_Call) Run(run func(ctx context.Context, appID string, envName string, opts client.AppModelDeployOptions)) *MockClient_CreateAppTafDeploy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 client.AppModelDeployOptions
		if args[3] != nil {
			arg3 = args[3].(client.AppModelDeployOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockClient_CreateAppTafDeploy_Call) Return(err error) *MockClient_CreateAppTafDeploy_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_CreateAppTafDeploy_Call) RunAndReturn(run func(ctx context.Context, appID string, envName string, opts client.AppModelDeployOptions) error) *MockClient_CreateAppTafDeploy_Call {
	_c.Call.Return(run)
	return _c
}

// CreateAppTrpcDeploy provides a mock function for the type MockClient
func (_mock *MockClient) CreateAppTrpcDeploy(ctx context.Context, appID string, envName string, opts client.AppModelDeployOptions) error {
	ret := _mock.Called(ctx, appID, envName, opts)

	if len(ret) == 0 {
		panic("no return value specified for CreateAppTrpcDeploy")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, client.AppModelDeployOptions) error); ok {
		r0 = returnFunc(ctx, appID, envName, opts)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_CreateAppTrpcDeploy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAppTrpcDeploy'
type MockClient_CreateAppTrpcDeploy_Call struct {
	*mock.Call
}

// CreateAppTrpcDeploy is a helper method to define mock.On call
//   - ctx context.Context
//   - appID string
//   - envName string
//   - opts client.AppModelDeployOptions
func (_e *MockClient_Expecter) CreateAppTrpcDeploy(ctx any, appID any, envName any, opts any) *MockClient_CreateAppTrpcDeploy_Call {
	return &MockClient_CreateAppTrpcDeploy_Call{Call: _e.mock.On("CreateAppTrpcDeploy", ctx, appID, envName, opts)}
}

func (_c *MockClient_CreateAppTrpcDeploy_Call) Run(run func(ctx context.Context, appID string, envName string, opts client.AppModelDeployOptions)) *MockClient_CreateAppTrpcDeploy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 client.AppModelDeployOptions
		if args[3] != nil {
			arg3 = args[3].(client.AppModelDeployOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockClient_CreateAppTrpcDeploy_Call) Return(err error) *MockClient_CreateAppTrpcDeploy_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_CreateAppTrpcDeploy_Call) RunAndReturn(run func(ctx context.Context, appID string, envName string, opts client.AppModelDeployOptions) error) *MockClient_CreateAppTrpcDeploy_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAppConfigFileVersion provides a mock function for the type MockClient
func (_mock *MockClient) DeleteAppConfigFileVersion(ctx context.Context, appID string, versionID string) error {
	ret := _mock.Called(ctx, appID, versionID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAppConfigFileVersion")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, appID, versionID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_DeleteAppConfigFileVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAppConfigFileVersion'
type MockClient_DeleteAppConfigFileVersion_Call struct {
	*mock.Call
}

// DeleteAppConfigFileVersion is a helper method to define mock.On call
//   - ctx context.Context
//   - appID string
//   - versionID string
func (_e *MockClient_Expecter) DeleteAppConfigFileVersion(ctx any, appID any, versionID any) *MockClient_DeleteAppConfigFileVersion_Call {
	return &MockClient_DeleteAppConfigFileVersion_Call{Call: _e.mock.On("DeleteAppConfigFileVersion", ctx, appID, versionID)}
}

func (_c *MockClient_DeleteAppConfigFileVersion_Call) Run(run func(ctx context.Context, appID string, versionID string)) *MockClient_DeleteAppConfigFileVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_DeleteAppConfigFileVersion_Call) Return(err error) *MockClient_DeleteAppConfigFileVersion_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_DeleteAppConfigFileVersion_Call) RunAndReturn(run func(ctx context.Context, appID string, versionID string) error) *MockClient_DeleteAppConfigFileVersion_Call {
	_c.Call.Return(run)
	return _c
}

// ExecuteTafAdminCmd provides a mock function for the type MockClient
func (_mock *MockClient) ExecuteTafAdminCmd(ctx context.Context, appID string, envName string, opts client.ExecuteTafAdminCmdOptions) ([]client.AdminCmdResult, error) {
	ret := _mock.Called(ctx, appID, envName, opts)

	if len(ret) == 0 {
		panic("no return value specified for ExecuteTafAdminCmd")
	}

	var r0 []client.AdminCmdResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, client.ExecuteTafAdminCmdOptions) ([]client.AdminCmdResult, error)); ok {
		return returnFunc(ctx, appID, envName, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, client.ExecuteTafAdminCmdOptions) []client.AdminCmdResult); ok {
		r0 = returnFunc(ctx, appID, envName, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]client.AdminCmdResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, client.ExecuteTafAdminCmdOptions) error); ok {
		r1 = returnFunc(ctx, appID, envName, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_ExecuteTafAdminCmd_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecuteTafAdminCmd'
type MockClient_ExecuteTafAdminCmd_Call struct {
	*mock.Call
}

// ExecuteTafAdminCmd is a helper method to define mock.On call
//   - ctx context.Context
//   - appID string
//   - envName string
//   - opts client.ExecuteTafAdminCmdOptions
func (_e *MockClient_Expecter) ExecuteTafAdminCmd(ctx any, appID any, envName any, opts any) *MockClient_ExecuteTafAdminCmd_Call {
	return &MockClient_ExecuteTafAdminCmd_Call{Call: _e.mock.On("ExecuteTafAdminCmd", ctx, appID, envName, opts)}
}

func (_c *MockClient_ExecuteTafAdminCmd_Call) Run(run func(ctx context.Context, appID string, envName string, opts client.ExecuteTafAdminCmdOptions)) *MockClient_ExecuteTafAdminCmd_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 client.ExecuteTafAdminCmdOptions
		if args[3] != nil {
			arg3 = args[3].(client.ExecuteTafAdminCmdOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockClient_ExecuteTafAdminCmd_Call) Return(adminCmdResults []client.AdminCmdResult, err error) *MockClient_ExecuteTafAdminCmd_Call {
	_c.Call.Return(adminCmdResults, err)
	return _c
}

func (_c *MockClient_ExecuteTafAdminCmd_Call) RunAndReturn(run func(ctx context.Context, appID string, envName string, opts client.ExecuteTafAdminCmdOptions) ([]client.AdminCmdResult, error)) *MockClient_ExecuteTafAdminCmd_Call {
	_c.Call.Return(run)
	return _c
}

// ExecuteTrpcAdminCmd provides a mock function for the type MockClient
func (_mock *MockClient) ExecuteTrpcAdminCmd(ctx context.Context, appID string, envName string, opts client.ExecuteTrpcAdminCmdOptions) ([]client.AdminCmdResult, error) {
	ret := _mock.Called(ctx, appID, envName, opts)

	if len(ret) == 0 {
		panic("no return value specified for ExecuteTrpcAdminCmd")
	}

	var r0 []client.AdminCmdResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, client.ExecuteTrpcAdminCmdOptions) ([]client.AdminCmdResult, error)); ok {
		return returnFunc(ctx, appID, envName, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, client.ExecuteTrpcAdminCmdOptions) []client.AdminCmdResult); ok {
		r0 = returnFunc(ctx, appID, envName, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]client.AdminCmdResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, client.ExecuteTrpcAdminCmdOptions) error); ok {
		r1 = returnFunc(ctx, appID, envName, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_ExecuteTrpcAdminCmd_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecuteTrpcAdminCmd'
type MockClient_ExecuteTrpcAdminCmd_Call struct {
	*mock.Call
}

// ExecuteTrpcAdminCmd is a helper method to define mock.On call
//   - ctx context.Context
//   - appID string
//   - envName string
//   - opts client.ExecuteTrpcAdminCmdOptions
func (_e *MockClient_Expecter) ExecuteTrpcAdminCmd(ctx any, appID any, envName any, opts any) *MockClient_ExecuteTrpcAdminCmd_Call {
	return &MockClient_ExecuteTrpcAdminCmd_Call{Call: _e.mock.On("ExecuteTrpcAdminCmd", ctx, appID, envName, opts)}
}

func (_c *MockClient_ExecuteTrpcAdminCmd_Call) Run(run func(ctx context.Context, appID string, envName string, opts client.ExecuteTrpcAdminCmdOptions)) *MockClient_ExecuteTrpcAdminCmd_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 client.ExecuteTrpcAdminCmdOptions
		if args[3] != nil {
			arg3 = args[3].(client.ExecuteTrpcAdminCmdOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockClient_ExecuteTrpcAdminCmd_Call) Return(adminCmdResults []client.AdminCmdResult, err error) *MockClient_ExecuteTrpcAdminCmd_Call {
	_c.Call.Return(adminCmdResults, err)
	return _c
}

func (_c *MockClient_ExecuteTrpcAdminCmd_Call) RunAndReturn(run func(ctx context.Context, appID string, envName string, opts client.ExecuteTrpcAdminCmdOptions) ([]client.AdminCmdResult, error)) *MockClient_ExecuteTrpcAdminCmd_Call {
	_c.Call.Return(run)
	return _c
}

// GetAppConfigFileDetails provides a mock function for the type MockClient
func (_mock *MockClient) GetAppConfigFileDetails(ctx context.Context, appID string, fileID string) (*client.AppConfigFileDetails, error) {
	ret := _mock.Called(ctx, appID, fileID)

	if len(ret) == 0 {
		panic("no return value specified for GetAppConfigFileDetails")
	}

	var r0 *client.AppConfigFileDetails
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*client.AppConfigFileDetails, error)); ok {
		return returnFunc(ctx, appID, fileID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *client.AppConfigFileDetails); ok {
		r0 = returnFunc(ctx, appID, fileID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.AppConfigFileDetails)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, appID, fileID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GetAppConfigFileDetails_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAppConfigFileDetails'
type MockClient_GetAppConfigFileDetails_Call struct {
	*mock.Call
}

// GetAppConfigFileDetails is a helper method to define mock.On call
//   - ctx context.Context
//   - appID string
//   - fileID string
func (_e *MockClient_Expecter) GetAppConfigFileDetails(ctx any, appID any, fileID any) *MockClient_GetAppConfigFileDetails_Call {
	return &MockClient_GetAppConfigFileDetails_Call{Call: _e.mock.On("GetAppConfigFileDetails", ctx, appID, fileID)}
}

func (_c *MockClient_GetAppConfigFileDetails_Call) Run(run func(ctx context.Context, appID string, fileID string)) *MockClient_GetAppConfigFileDetails_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_GetAppConfigFileDetails_Call) Return(appConfigFileDetails *client.AppConfigFileDetails, err error) *MockClient_GetAppConfigFileDetails_Call {
	_c.Call.Return(appConfigFileDetails, err)
	return _c
}

func (_c *MockClient_GetAppConfigFileDetails_Call) RunAndReturn(run func(ctx context.Context, appID string, fileID string) (*client.AppConfigFileDetails, error)) *MockClient_GetAppConfigFileDetails_Call {
	_c.Call.Return(run)
	return _c
}

// GetAppConfigFileVersion provides a mock function for the type MockClient
func (_mock *MockClient) GetAppConfigFileVersion(ctx context.Context, appID string, versionID string) (*client.AppConfigFileVersion, error) {
	ret := _mock.Called(ctx, appID, versionID)

	if len(ret) == 0 {
		panic("no return value specified for GetAppConfigFileVersion")
	}

	var r0 *client.AppConfigFileVersion
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*client.AppConfigFileVersion, error)); ok {
		return returnFunc(ctx, appID, versionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *client.AppConfigFileVersion); ok {
		r0 = returnFunc(ctx, appID, versionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.AppConfigFileVersion)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, appID, versionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GetAppConfigFileVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAppConfigFileVersion'
type MockClient_GetAppConfigFileVersion_Call struct {
	*mock.Call
}

// GetAppConfigFileVersion is a helper method to define mock.On call
//   - ctx context.Context
//   - appID string
//   - versionID string
func (_e *MockClient_Expecter) GetAppConfigFileVersion(ctx any, appID any, versionID any) *MockClient_GetAppConfigFileVersion_Call {
	return &MockClient_GetAppConfigFileVersion_Call{Call: _e.mock.On("GetAppConfigFileVersion", ctx, appID, versionID)}
}

func (_c *MockClient_GetAppConfigFileVersion_Call) Run(run func(ctx context.Context, appID string, versionID string)) *MockClient_GetAppConfigFileVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_GetAppConfigFileVersion_Call) Return(appConfigFileVersion *client.AppConfigFileVersion, err error) *MockClient_GetAppConfigFileVersion_Call {
	_c.Call.Return(appConfigFileVersion, err)
	return _c
}

func (_c *MockClient_GetAppConfigFileVersion_Call) RunAndReturn(run func(ctx context.Context, appID string, versionID string) (*client.AppConfigFileVersion, error)) *MockClient_GetAppConfigFileVersion_Call {
	_c.Call.Return(run)
	return _c
}

// GetAppIDAutoSuffix provides a mock function for the type MockClient
func (_mock *MockClient) GetAppIDAutoSuffix(ctx context.Context) (string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAppIDAutoSuffix")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GetAppIDAutoSuffix_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAppIDAutoSuffix'
type MockClient_GetAppIDAutoSuffix_Call struct {
	*mock.Call
}

// GetAppIDAutoSuffix is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockClient_Expecter) GetAppIDAutoSuffix(ctx any) *MockClient_GetAppIDAutoSuffix_Call {
	return &MockClient_GetAppIDAutoSuffix_Call{Call: _e.mock.On("GetAppIDAutoSuffix", ctx)}
}

func (_c *MockClient_GetAppIDAutoSuffix_Call) Run(run func(ctx context.Context)) *MockClient_GetAppIDAutoSuffix_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClient_GetAppIDAutoSuffix_Call) Return(s string, err error) *MockClient_GetAppIDAutoSuffix_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockClient_GetAppIDAutoSuffix_Call) RunAndReturn(run func(ctx context.Context) (string, error)) *MockClient_GetAppIDAutoSuffix_Call {
	_c.Call.Return(run)
	return _c
}

// GetAppMinimal provides a mock function for the type MockClient
func (_mock *MockClient) GetAppMinimal(ctx context.Context, workspaceID string, appID string) (*client.AppMinimal, error) {
	ret := _mock.Called(ctx, workspaceID, appID)

	if len(ret) == 0 {
		panic("no return value specified for GetAppMinimal")
	}

	var r0 *client.AppMinimal
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*client.AppMinimal, error)); ok {
		return returnFunc(ctx, workspaceID, appID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *client.AppMinimal); ok {
		r0 = returnFunc(ctx, workspaceID, appID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.AppMinimal)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, workspaceID, appID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GetAppMinimal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAppMinimal'
type MockClient_GetAppMinimal_Call struct {
	*mock.Call
}

// GetAppMinimal is a helper method to define mock.On call
//   - ctx context.Context
//   - workspaceID string
//   - appID string
func (_e *MockClient_Expecter) GetAppMinimal(ctx any, workspaceID any, appID any) *MockClient_GetAppMinimal_Call {
	return &MockClient_GetAppMinimal_Call{Call: _e.mock.On("GetAppMinimal", ctx, workspaceID, appID)}
}

func (_c *MockClient_GetAppMinimal_Call) Run(run func(ctx context.Context, workspaceID string, appID string)) *MockClient_GetAppMinimal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_GetAppMinimal_Call) Return(appMinimal *client.AppMinimal, err error) *MockClient_GetAppMinimal_Call {
	_c.Call.Return(appMinimal, err)
	return _c
}

func (_c *MockClient_GetAppMinimal_Call) RunAndReturn(run func(ctx context.Context, workspaceID string, appID string) (*client.AppMinimal, error)) *MockClient_GetAppMinimal_Call {
	_c.Call.Return(run)
	return _c
}

// GetEnvEffectiveDevMode provides a mock function for the type MockClient
func (_mock *MockClient) GetEnvEffectiveDevMode(ctx context.Context, appID string, envName string) (*client.DevModeConfig, error) {
	ret := _mock.Called(ctx, appID, envName)

	if len(ret) == 0 {
		panic("no return value specified for GetEnvEffectiveDevMode")
	}

	var r0 *client.DevModeConfig
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*client.DevModeConfig, error)); ok {
		return returnFunc(ctx, appID, envName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *client.DevModeConfig); ok {
		r0 = returnFunc(ctx, appID, envName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.DevModeConfig)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, appID, envName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GetEnvEffectiveDevMode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEnvEffectiveDevMode'
type MockClient_GetEnvEffectiveDevMode_Call struct {
	*mock.Call
}

// GetEnvEffectiveDevMode is a helper method to define mock.On call
//   - ctx context.Context
//   - appID string
//   - envName string
func (_e *MockClient_Expecter) GetEnvEffectiveDevMode(ctx any, appID any, envName any) *MockClient_GetEnvEffectiveDevMode_Call {
	return &MockClient_GetEnvEffectiveDevMode_Call{Call: _e.mock.On("GetEnvEffectiveDevMode", ctx, appID, envName)}
}

func (_c *MockClient_GetEnvEffectiveDevMode_Call) Run(run func(ctx context.Context, appID string, envName string)) *MockClient_GetEnvEffectiveDevMode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_GetEnvEffectiveDevMode_Call) Return(devModeConfig *client.DevModeConfig, err error) *MockClient_GetEnvEffectiveDevMode_Call {
	_c.Call.Return(devModeConfig, err)
	return _c
}

func (_c *MockClient_GetEnvEffectiveDevMode_Call) RunAndReturn(run func(ctx context.Context, appID string, envName string) (*client.DevModeConfig, error)) *MockClient_GetEnvEffectiveDevMode_Call {
	_c.Call.Return(run)
	return _c
}

// GetWorkspace provides a mock function for the type MockClient
func (_mock *MockClient) GetWorkspace(ctx context.Context, id string) (*client.Workspace, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetWorkspace")
	}

	var r0 *client.Workspace
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*client.Workspace, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *client.Workspace); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.Workspace)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GetWorkspace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWorkspace'
type MockClient_GetWorkspace_Call struct {
	*mock.Call
}

// GetWorkspace is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockClient_Expecter) GetWorkspace(ctx any, id any) *MockClient_GetWorkspace_Call {
	return &MockClient_GetWorkspace_Call{Call: _e.mock.On("GetWorkspace", ctx, id)}
}

func (_c *MockClient_GetWorkspace_Call) Run(run func(ctx context.Context, id string)) *MockClient_GetWorkspace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_GetWorkspace_Call) Return(workspace *client.Workspace, err error) *MockClient_GetWorkspace_Call {
	_c.Call.Return(workspace, err)
	return _c
}

func (_c *MockClient_GetWorkspace_Call) RunAndReturn(run func(ctx context.Context, id string) (*client.Workspace, error)) *MockClient_GetWorkspace_Call {
	_c.Call.Return(run)
	return _c
}

// GrayscaleUpdateInstance provides a mock function for the type MockClient
func (_mock *MockClient) GrayscaleUpdateInstance(ctx context.Context, appID string, envName string, imageTag string, instanceIDs []string, updateStrategy string) error {
	ret := _mock.Called(ctx, appID, envName, imageTag, instanceIDs, updateStrategy)

	if len(ret) == 0 {
		panic("no return value specified for GrayscaleUpdateInstance")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, []string, string) error); ok {
		r0 = returnFunc(ctx, appID, envName, imageTag, instanceIDs, updateStrategy)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_GrayscaleUpdateInstance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GrayscaleUpdateInstance'
type MockClient_GrayscaleUpdateInstance_Call struct {
	*mock.Call
}

// GrayscaleUpdateInstance is a helper method to define mock.On call
//   - ctx context.Context
//   - appID string
//   - envName string
//   - imageTag string
//   - instanceIDs []string
//   - updateStrategy string
func (_e *MockClient_Expecter) GrayscaleUpdateInstance(ctx any, appID any, envName any, imageTag any, instanceIDs any, updateStrategy any) *MockClient_GrayscaleUpdateInstance_Call {
	return &MockClient_GrayscaleUpdateInstance_Call{Call: _e.mock.On("GrayscaleUpdateInstance", ctx, appID, envName, imageTag, instanceIDs, updateStrategy)}
}

func (_c *MockClient_GrayscaleUpdateInstance_Call) Run(run func(ctx context.Context, appID string, envName string, imageTag string, instanceIDs []string, updateStrategy string)) *MockClient_GrayscaleUpdateInstance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 []string
		if args[4] != nil {
			arg4 = args[4].([]string)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockClient_GrayscaleUpdateInstance_Call) Return(err error) *MockClient_GrayscaleUpdateInstance_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_GrayscaleUpdateInstance_Call) RunAndReturn(run func(ctx context.Context, appID string, envName string, imageTag string, instanceIDs []string, updateStrategy string) error) *MockClient_GrayscaleUpdateInstance_Call {
	_c.Call.Return(run)
	return _c
}

// ListAppConfigFileVersions provides a mock function for the type MockClient
func (_mock *MockClient) ListAppConfigFileVersions(ctx context.Context, appID string, opts client.ListAppConfigFileVersionsOptions) (*client.PaginatedAppConfigFileVersions, error) {
	ret := _mock.Called(ctx, appID, opts)

	if len(ret) == 0 {
		panic("no return value specified for ListAppConfigFileVersions")
	}

	var r0 *client.PaginatedAppConfigFileVersions
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, client.ListAppConfigFileVersionsOptions) (*client.PaginatedAppConfigFileVersions, error)); ok {
		return returnFunc(ctx, appID, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, client.ListAppConfigFileVersionsOptions) *client.PaginatedAppConfigFileVersions); ok {
		r0 = returnFunc(ctx, appID, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.PaginatedAppConfigFileVersions)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, client.ListAppConfigFileVersionsOptions) error); ok {
		r1 = returnFunc(ctx, appID, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_ListAppConfigFileVersions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAppConfigFileVersions'
type MockClient_ListAppConfigFileVersions_Call struct {
	*mock.Call
}

// ListAppConfigFileVersions is a helper method to define mock.On call
//   - ctx context.Context
//   - appID string
//   - opts client.ListAppConfigFileVersionsOptions
func (_e *MockClient_Expecter) ListAppConfigFileVersions(ctx any, appID any, opts any) *MockClient_ListAppConfigFileVersions_Call {
	return &MockClient_ListAppConfigFileVersions_Call{Call: _e.mock.On("ListAppConfigFileVersions", ctx, appID, opts)}
}

func (_c *MockClient_ListAppConfigFileVersions_Call) Run(run func(ctx context.Context, appID string, opts client.ListAppConfigFileVersionsOptions)) *MockClient_ListAppConfigFileVersions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 client.ListAppConfigFileVersionsOptions
		if args[2] != nil {
			arg2 = args[2].(client.ListAppConfigFileVersionsOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_ListAppConfigFileVersions_Call) Return(paginatedAppConfigFileVersions *client.PaginatedAppConfigFileVersions, err error) *MockClient_ListAppConfigFileVersions_Call {
	_c.Call.Return(paginatedAppConfigFileVersions, err)
	return _c
}

func (_c *MockClient_ListAppConfigFileVersions_Call) RunAndReturn(run func(ctx context.Context, appID string, opts client.ListAppConfigFileVersionsOptions) (*client.PaginatedAppConfigFileVersions, error)) *MockClient_ListAppConfigFileVersions_Call {
	_c.Call.Return(run)
	return _c
}

// ListAppConfigFiles provides a mock function for the type MockClient
func (_mock *MockClient) ListAppConfigFiles(ctx context.Context, appID string, envName string) ([]client.AppConfigFile, error) {
	ret := _mock.Called(ctx, appID, envName)

	if len(ret) == 0 {
		panic("no return value specified for ListAppConfigFiles")
	}

	var r0 []client.AppConfigFile
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]client.AppConfigFile, error)); ok {
		return returnFunc(ctx, appID, envName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []client.AppConfigFile); ok {
		r0 = returnFunc(ctx, appID, envName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]client.AppConfigFile)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, appID, envName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_ListAppConfigFiles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAppConfigFiles'
type MockClient_ListAppConfigFiles_Call struct {
	*mock.Call
}

// ListAppConfigFiles is a helper method to define mock.On call
//   - ctx context.Context
//   - appID string
//   - envName string
func (_e *MockClient_Expecter) ListAppConfigFiles(ctx any, appID any, envName any) *MockClient_ListAppConfigFiles_Call {
	return &MockClient_ListAppConfigFiles_Call{Call: _e.mock.On("ListAppConfigFiles", ctx, appID, envName)}
}

func (_c *MockClient_ListAppConfigFiles_Call) Run(run func(ctx context.Context, appID string, envName string)) *MockClient_ListAppConfigFiles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_ListAppConfigFiles_Call) Return(appConfigFiles []client.AppConfigFile, err error) *MockClient_ListAppConfigFiles_Call {
	_c.Call.Return(appConfigFiles, err)
	return _c
}

func (_c *MockClient_ListAppConfigFiles_Call) RunAndReturn(run func(ctx context.Context, appID string, envName string) ([]client.AppConfigFile, error)) *MockClient_ListAppConfigFiles_Call {
	_c.Call.Return(run)
	return _c
}

// ListAppImages provides a mock function for the type MockClient
func (_mock *MockClient) ListAppImages(ctx context.Context, appID string, keyword string) ([]client.Image, error) {
	ret := _mock.Called(ctx, appID, keyword)

	if len(ret) == 0 {
		panic("no return value specified for ListAppImages")
	}

	var r0 []client.Image
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]client.Image, error)); ok {
		return returnFunc(ctx, appID, keyword)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []client.Image); ok {
		r0 = returnFunc(ctx, appID, keyword)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]client.Image)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, appID, keyword)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_ListAppImages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAppImages'
type MockClient_ListAppImages_Call struct {
	*mock.Call
}

// ListAppImages is a helper method to define mock.On call
//   - ctx context.Context
//   - appID string
//   - keyword string
func (_e *MockClient_Expecter) ListAppImages(ctx any, appID any, keyword any) *MockClient_ListAppImages_Call {
	return &MockClient_ListAppImages_Call{Call: _e.mock.On("ListAppImages", ctx, appID, keyword)}
}

func (_c *MockClient_ListAppImages_Call) Run(run func(ctx context.Context, appID string, keyword string)) *MockClient_ListAppImages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_ListAppImages_Call) Return(images []client.Image, err error) *MockClient_ListAppImages_Call {
	_c.Call.Return(images, err)
	return _c
}

func (_c *MockClient_ListAppImages_Call) RunAndReturn(run func(ctx context.Context, appID string, keyword string) ([]client.Image, error)) *MockClient_ListAppImages_Call {
	_c.Call.Return(run)
	return _c
}

// ListAppInstances provides a mock function for the type MockClient
func (_mock *MockClient) ListAppInstances(ctx context.Context, appID string, envName string, opts client.ListAppInstancesOptions) (*client.PaginatedInstances, error) {
	ret := _mock.Called(ctx, appID, envName, opts)

	if len(ret) == 0 {
		panic("no return value specified for ListAppInstances")
	}

	var r0 *client.PaginatedInstances
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, client.ListAppInstancesOptions) (*client.PaginatedInstances, error)); ok {
		return returnFunc(ctx, appID, envName, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, client.ListAppInstancesOptions) *client.PaginatedInstances); ok {
		r0 = returnFunc(ctx, appID, envName, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.PaginatedInstances)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, client.ListAppInstancesOptions) error); ok {
		r1 = returnFunc(ctx, appID, envName, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_ListAppInstances_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAppInstances'
type MockClient_ListAppInstances_Call struct {
	*mock.Call
}

// ListAppInstances is a helper method to define mock.On call
//   - ctx context.Context
//   - appID string
//   - envName string
//   - opts client.ListAppInstancesOptions
func (_e *MockClient_Expecter) ListAppInstances(ctx any, appID any, envName any, opts any) *MockClient_ListAppInstances_Call {
	return &MockClient_ListAppInstances_Call{Call: _e.mock.On("ListAppInstances", ctx, appID, envName, opts)}
}

func (_c *MockClient_ListAppInstances_Call) Run(run func(ctx context.Context, appID string, envName string, opts client.ListAppInstancesOptions)) *MockClient_ListAppInstances_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 client.ListAppInstancesOptions
		if args[3] != nil {
			arg3 = args[3].(client.ListAppInstancesOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockClient_ListAppInstances_Call) Return(paginatedInstances *client.PaginatedInstances, err error) *MockClient_ListAppInstances_Call {
	_c.Call.Return(paginatedInstances, err)
	return _c
}

func (_c *MockClient_ListAppInstances_Call) RunAndReturn(run func(ctx context.Context, appID string, envName string, opts client.ListAppInstancesOptions) (*client.PaginatedInstances, error)) *MockClient_ListAppInstances_Call {
	_c.Call.Return(run)
	return _c
}

// ListApps provides a mock function for the type MockClient
func (_mock *MockClient) ListApps(ctx context.Context, workspaceID string) ([]client.AppMinimal, error) {
	ret := _mock.Called(ctx, workspaceID)

	if len(ret) == 0 {
		panic("no return value specified for ListApps")
	}

	var r0 []client.AppMinimal
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]client.AppMinimal, error)); ok {
		return returnFunc(ctx, workspaceID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []client.AppMinimal); ok {
		r0 = returnFunc(ctx, workspaceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]client.AppMinimal)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, workspaceID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_ListApps_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListApps'
type MockClient_ListApps_Call struct {
	*mock.Call
}

// ListApps is a helper method to define mock.On call
//   - ctx context.Context
//   - workspaceID string
func (_e *MockClient_Expecter) ListApps(ctx any, workspaceID any) *MockClient_ListApps_Call {
	return &MockClient_ListApps_Call{Call: _e.mock.On("ListApps", ctx, workspaceID)}
}

func (_c *MockClient_ListApps_Call) Run(run func(ctx context.Context, workspaceID string)) *MockClient_ListApps_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_ListApps_Call) Return(appMinimals []client.AppMinimal, err error) *MockClient_ListApps_Call {
	_c.Call.Return(appMinimals, err)
	return _c
}

func (_c *MockClient_ListApps_Call) RunAndReturn(run func(ctx context.Context, workspaceID string) ([]client.AppMinimal, error)) *MockClient_ListApps_Call {
	_c.Call.Return(run)
	return _c
}

// ListBuildRecords provides a mock function for the type MockClient
func (_mock *MockClient) ListBuildRecords(ctx context.Context, appID string, keyword string) ([]client.BuildRecord, error) {
	ret := _mock.Called(ctx, appID, keyword)

	if len(ret) == 0 {
		panic("no return value specified for ListBuildRecords")
	}

	var r0 []client.BuildRecord
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]client.BuildRecord, error)); ok {
		return returnFunc(ctx, appID, keyword)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []client.BuildRecord); ok {
		r0 = returnFunc(ctx, appID, keyword)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]client.BuildRecord)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, appID, keyword)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_ListBuildRecords_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListBuildRecords'
type MockClient_ListBuildRecords_Call struct {
	*mock.Call
}

// ListBuildRecords is a helper method to define mock.On call
//   - ctx context.Context
//   - appID string
//   - keyword string
func (_e *MockClient_Expecter) ListBuildRecords(ctx any, appID any, keyword any) *MockClient_ListBuildRecords_Call {
	return &MockClient_ListBuildRecords_Call{Call: _e.mock.On("ListBuildRecords", ctx, appID, keyword)}
}

func (_c *MockClient_ListBuildRecords_Call) Run(run func(ctx context.Context, appID string, keyword string)) *MockClient_ListBuildRecords_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_ListBuildRecords_Call) Return(buildRecords []client.BuildRecord, err error) *MockClient_ListBuildRecords_Call {
	_c.Call.Return(buildRecords, err)
	return _c
}

func (_c *MockClient_ListBuildRecords_Call) RunAndReturn(run func(ctx context.Context, appID string, keyword string) ([]client.BuildRecord, error)) *MockClient_ListBuildRecords_Call {
	_c.Call.Return(run)
	return _c
}

// ListEnvs provides a mock function for the type MockClient
func (_mock *MockClient) ListEnvs(ctx context.Context, workspaceID string) ([]client.Env, error) {
	ret := _mock.Called(ctx, workspaceID)

	if len(ret) == 0 {
		panic("no return value specified for ListEnvs")
	}

	var r0 []client.Env
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]client.Env, error)); ok {
		return returnFunc(ctx, workspaceID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []client.Env); ok {
		r0 = returnFunc(ctx, workspaceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]client.Env)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, workspaceID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_ListEnvs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListEnvs'
type MockClient_ListEnvs_Call struct {
	*mock.Call
}

// ListEnvs is a helper method to define mock.On call
//   - ctx context.Context
//   - workspaceID string
func (_e *MockClient_Expecter) ListEnvs(ctx any, workspaceID any) *MockClient_ListEnvs_Call {
	return &MockClient_ListEnvs_Call{Call: _e.mock.On("ListEnvs", ctx, workspaceID)}
}

func (_c *MockClient_ListEnvs_Call) Run(run func(ctx context.Context, workspaceID string)) *MockClient_ListEnvs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_ListEnvs_Call) Return(envs []client.Env, err error) *MockClient_ListEnvs_Call {
	_c.Call.Return(envs, err)
	return _c
}

func (_c *MockClient_ListEnvs_Call) RunAndReturn(run func(ctx context.Context, workspaceID string) ([]client.Env, error)) *MockClient_ListEnvs_Call {
	_c.Call.Return(run)
	return _c
}

// ListHelmDeployRecords provides a mock function for the type MockClient
func (_mock *MockClient) ListHelmDeployRecords(ctx context.Context, appID string, envName string, trafficLaneName string, keyword string) ([]client.HelmDeployRecord, error) {
	ret := _mock.Called(ctx, appID, envName, trafficLaneName, keyword)

	if len(ret) == 0 {
		panic("no return value specified for ListHelmDeployRecords")
	}

	var r0 []client.HelmDeployRecord
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) ([]client.HelmDeployRecord, error)); ok {
		return returnFunc(ctx, appID, envName, trafficLaneName, keyword)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) []client.HelmDeployRecord); ok {
		r0 = returnFunc(ctx, appID, envName, trafficLaneName, keyword)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]client.HelmDeployRecord)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, string) error); ok {
		r1 = returnFunc(ctx, appID, envName, trafficLaneName, keyword)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_ListHelmDeployRecords_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListHelmDeployRecords'
type MockClient_ListHelmDeployRecords_Call struct {
	*mock.Call
}

// ListHelmDeployRecords is a helper method to define mock.On call
//   - ctx context.Context
//   - appID string
//   - envName string
//   - trafficLaneName string
//   - keyword string
func (_e *MockClient_Expecter) ListHelmDeployRecords(ctx any, appID any, envName any, trafficLaneName any, keyword any) *MockClient_ListHelmDeployRecords_Call {
	return &MockClient_ListHelmDeployRecords_Call{Call: _e.mock.On("ListHelmDeployRecords", ctx, appID, envName, trafficLaneName, keyword)}
}

func (_c *MockClient_ListHelmDeployRecords_Call) Run(run func(ctx context.Context, appID string, envName string, trafficLaneName string, keyword string)) *MockClient_ListHelmDeployRecords_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockClient_ListHelmDeployRecords_Call) Return(helmDeployRecords []client.HelmDeployRecord, err error) *MockClient_ListHelmDeployRecords_Call {
	_c.Call.Return(helmDeployRecords, err)
	return _c
}

func (_c *MockClient_ListHelmDeployRecords_Call) RunAndReturn(run func(ctx context.Context, appID string, envName string, trafficLaneName string, keyword string) ([]client.HelmDeployRecord, error)) *MockClient_ListHelmDeployRecords_Call {
	_c.Call.Return(run)
	return _c
}

// ListTafDeployRecords provides a mock function for the type MockClient
func (_mock *MockClient) ListTafDeployRecords(ctx context.Context, appID string, envName string, keyword string, trafficLaneName string) ([]client.AppModelDeployRecord, error) {
	ret := _mock.Called(ctx, appID, envName, keyword, trafficLaneName)

	if len(ret) == 0 {
		panic("no return value specified for ListTafDeployRecords")
	}

	var r0 []client.AppModelDeployRecord
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) ([]client.AppModelDeployRecord, error)); ok {
		return returnFunc(ctx, appID, envName, keyword, trafficLaneName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) []client.AppModelDeployRecord); ok {
		r0 = returnFunc(ctx, appID, envName, keyword, trafficLaneName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]client.AppModelDeployRecord)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, string) error); ok {
		r1 = returnFunc(ctx, appID, envName, keyword, trafficLaneName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_ListTafDeployRecords_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTafDeployRecords'
type MockClient_ListTafDeployRecords_Call struct {
	*mock.Call
}

// ListTafDeployRecords is a helper method to define mock.On call
//   - ctx context.Context
//   - appID string
//   - envName string
//   - keyword string
//   - trafficLaneName string
func (_e *MockClient_Expecter) ListTafDeployRecords(ctx any, appID any, envName any, keyword any, trafficLaneName any) *MockClient_ListTafDeployRecords_Call {
	return &MockClient_ListTafDeployRecords_Call{Call: _e.mock.On("ListTafDeployRecords", ctx, appID, envName, keyword, trafficLaneName)}
}

func (_c *MockClient_ListTafDeployRecords_Call) Run(run func(ctx context.Context, appID string, envName string, keyword string, trafficLaneName string)) *MockClient_ListTafDeployRecords_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockClient_ListTafDeployRecords_Call) Return(appModelDeployRecords []client.AppModelDeployRecord, err error) *MockClient_ListTafDeployRecords_Call {
	_c.Call.Return(appModelDeployRecords, err)
	return _c
}

func (_c *MockClient_ListTafDeployRecords_Call) RunAndReturn(run func(ctx context.Context, appID string, envName string, keyword string, trafficLaneName string) ([]client.AppModelDeployRecord, error)) *MockClient_ListTafDeployRecords_Call {
	_c.Call.Return(run)
	return _c
}

// ListTrpcAdminCmds provides a mock function for the type MockClient
func (_mock *MockClient) ListTrpcAdminCmds(ctx context.Context, appID string, envName string, instanceIDs []string) ([]string, error) {
	ret := _mock.Called(ctx, appID, envName, instanceIDs)

	if len(ret) == 0 {
		panic("no return value specified for ListTrpcAdminCmds")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, []string) ([]string, error)); ok {
		return returnFunc(ctx, appID, envName, instanceIDs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, []string) []string); ok {
		r0 = returnFunc(ctx, appID, envName, instanceIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, []string) error); ok {
		r1 = returnFunc(ctx, appID, envName, instanceIDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_ListTrpcAdminCmds_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTrpcAdminCmds'
type MockClient_ListTrpcAdminCmds_Call struct {
	*mock.Call
}

// ListTrpcAdminCmds is a helper method to define mock.On call
//   - ctx context.Context
//   - appID string
//   - envName string
//   - instanceIDs []string
func (_e *MockClient_Expecter) ListTrpcAdminCmds(ctx any, appID any, envName any, instanceIDs any) *MockClient_ListTrpcAdminCmds_Call {
	return &MockClient_ListTrpcAdminCmds_Call{Call: _e.mock.On("ListTrpcAdminCmds", ctx, appID, envName, instanceIDs)}
}

func (_c *MockClient_ListTrpcAdminCmds_Call) Run(run func(ctx context.Context, appID string, envName string, instanceIDs []string)) *MockClient_ListTrpcAdminCmds_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []string
		if args[3] != nil {
			arg3 = args[3].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockClient_ListTrpcAdminCmds_Call) Return(strings []string, err error) *MockClient_ListTrpcAdminCmds_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockClient_ListTrpcAdminCmds_Call) RunAndReturn(run func(ctx context.Context, appID string, envName string, instanceIDs []string) ([]string, error)) *MockClient_ListTrpcAdminCmds_Call {
	_c.Call.Return(run)
	return _c
}

// ListTrpcDeployRecords provides a mock function for the type MockClient
func (_mock *MockClient) ListTrpcDeployRecords(ctx context.Context, appID string, envName string, keyword string, trafficLaneName string) ([]client.AppModelDeployRecord, error) {
	ret := _mock.Called(ctx, appID, envName, keyword, trafficLaneName)

	if len(ret) == 0 {
		panic("no return value specified for ListTrpcDeployRecords")
	}

	var r0 []client.AppModelDeployRecord
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) ([]client.AppModelDeployRecord, error)); ok {
		return returnFunc(ctx, appID, envName, keyword, trafficLaneName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) []client.AppModelDeployRecord); ok {
		r0 = returnFunc(ctx, appID, envName, keyword, trafficLaneName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]client.AppModelDeployRecord)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, string) error); ok {
		r1 = returnFunc(ctx, appID, envName, keyword, trafficLaneName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_ListTrpcDeployRecords_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTrpcDeployRecords'
type MockClient_ListTrpcDeployRecords_Call struct {
	*mock.Call
}

// ListTrpcDeployRecords is a helper method to define mock.On call
//   - ctx context.Context
//   - appID string
//   - envName string
//   - keyword string
//   - trafficLaneName string
func (_e *MockClient_Expecter) ListTrpcDeployRecords(ctx any, appID any, envName any, keyword any, trafficLaneName any) *MockClient_ListTrpcDeployRecords_Call {
	return &MockClient_ListTrpcDeployRecords_Call{Call: _e.mock.On("ListTrpcDeployRecords", ctx, appID, envName, keyword, trafficLaneName)}
}

func (_c *MockClient_ListTrpcDeployRecords_Call) Run(run func(ctx context.Context, appID string, envName string, keyword string, trafficLaneName string)) *MockClient_ListTrpcDeployRecords_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockClient_ListTrpcDeployRecords_Call) Return(appModelDeployRecords []client.AppModelDeployRecord, err error) *MockClient_ListTrpcDeployRecords_Call {
	_c.Call.Return(appModelDeployRecords, err)
	return _c
}

func (_c *MockClient_ListTrpcDeployRecords_Call) RunAndReturn(run func(ctx context.Context, appID string, envName string, keyword string, trafficLaneName string) ([]client.AppModelDeployRecord, error)) *MockClient_ListTrpcDeployRecords_Call {
	_c.Call.Return(run)
	return _c
}

// ListWorkspaces provides a mock function for the type MockClient
func (_mock *MockClient) ListWorkspaces(ctx context.Context, keyword string) ([]client.Workspace, error) {
	ret := _mock.Called(ctx, keyword)

	if len(ret) == 0 {
		panic("no return value specified for ListWorkspaces")
	}

	var r0 []client.Workspace
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]client.Workspace, error)); ok {
		return returnFunc(ctx, keyword)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []client.Workspace); ok {
		r0 = returnFunc(ctx, keyword)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]client.Workspace)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, keyword)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_ListWorkspaces_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListWorkspaces'
type MockClient_ListWorkspaces_Call struct {
	*mock.Call
}

// ListWorkspaces is a helper method to define mock.On call
//   - ctx context.Context
//   - keyword string
func (_e *MockClient_Expecter) ListWorkspaces(ctx any, keyword any) *MockClient_ListWorkspaces_Call {
	return &MockClient_ListWorkspaces_Call{Call: _e.mock.On("ListWorkspaces", ctx, keyword)}
}

func (_c *MockClient_ListWorkspaces_Call) Run(run func(ctx context.Context, keyword string)) *MockClient_ListWorkspaces_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_ListWorkspaces_Call) Return(workspaces []client.Workspace, err error) *MockClient_ListWorkspaces_Call {
	_c.Call.Return(workspaces, err)
	return _c
}

func (_c *MockClient_ListWorkspaces_Call) RunAndReturn(run func(ctx context.Context, keyword string) ([]client.Workspace, error)) *MockClient_ListWorkspaces_Call {
	_c.Call.Return(run)
	return _c
}

// OpenPortForwardTunnel provides a mock function for the type MockClient
// CheckPortForwardPermission provides a mock function for the type MockClient
func (_mock *MockClient) CheckPortForwardPermission(ctx context.Context, appID string, envName string, instanceID string, remotePort int, localPort int) error {
	ret := _mock.Called(ctx, appID, envName, instanceID, remotePort, localPort)

	if len(ret) == 0 {
		panic("no return value specified for CheckPortForwardPermission")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, int, int) error); ok {
		r0 = returnFunc(ctx, appID, envName, instanceID, remotePort, localPort)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_CheckPortForwardPermission_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckPortForwardPermission'
type MockClient_CheckPortForwardPermission_Call struct {
	*mock.Call
}

// CheckPortForwardPermission is a helper method to define mock.On call
//   - ctx context.Context
//   - appID string
//   - envName string
//   - instanceID string
//   - remotePort int
//   - localPort int
func (_e *MockClient_Expecter) CheckPortForwardPermission(ctx any, appID any, envName any, instanceID any, remotePort any, localPort any) *MockClient_CheckPortForwardPermission_Call {
	return &MockClient_CheckPortForwardPermission_Call{Call: _e.mock.On("CheckPortForwardPermission", ctx, appID, envName, instanceID, remotePort, localPort)}
}

func (_c *MockClient_CheckPortForwardPermission_Call) Run(run func(ctx context.Context, appID string, envName string, instanceID string, remotePort int, localPort int)) *MockClient_CheckPortForwardPermission_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		var arg5 int
		if args[5] != nil {
			arg5 = args[5].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockClient_CheckPortForwardPermission_Call) Return(err error) *MockClient_CheckPortForwardPermission_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_CheckPortForwardPermission_Call) RunAndReturn(run func(ctx context.Context, appID string, envName string, instanceID string, remotePort int, localPort int) error) *MockClient_CheckPortForwardPermission_Call {
	_c.Call.Return(run)
	return _c
}

// OpenPortForwardTunnel provides a mock function for the type MockClient
func (_mock *MockClient) OpenPortForwardTunnel(ctx context.Context, appID string, envName string, opts client.PortForwardTunnelOptions) (io.ReadWriteCloser, error) {
	ret := _mock.Called(ctx, appID, envName, opts)

	if len(ret) == 0 {
		panic("no return value specified for OpenPortForwardTunnel")
	}

	var r0 io.ReadWriteCloser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, client.PortForwardTunnelOptions) (io.ReadWriteCloser, error)); ok {
		return returnFunc(ctx, appID, envName, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, client.PortForwardTunnelOptions) io.ReadWriteCloser); ok {
		r0 = returnFunc(ctx, appID, envName, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadWriteCloser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, client.PortForwardTunnelOptions) error); ok {
		r1 = returnFunc(ctx, appID, envName, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_OpenPortForwardTunnel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OpenPortForwardTunnel'
type MockClient_OpenPortForwardTunnel_Call struct {
	*mock.Call
}

// OpenPortForwardTunnel is a helper method to define mock.On call
//   - ctx context.Context
//   - appID string
//   - envName string
//   - opts client.PortForwardTunnelOptions
func (_e *MockClient_Expecter) OpenPortForwardTunnel(ctx any, appID any, envName any, opts any) *MockClient_OpenPortForwardTunnel_Call {
	return &MockClient_OpenPortForwardTunnel_Call{Call: _e.mock.On("OpenPortForwardTunnel", ctx, appID, envName, opts)}
}

func (_c *MockClient_OpenPortForwardTunnel_Call) Run(run func(ctx context.Context, appID string, envName string, opts client.PortForwardTunnelOptions)) *MockClient_OpenPortForwardTunnel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 client.PortForwardTunnelOptions
		if args[3] != nil {
			arg3 = args[3].(client.PortForwardTunnelOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockClient_OpenPortForwardTunnel_Call) Return(readWriteCloser io.ReadWriteCloser, err error) *MockClient_OpenPortForwardTunnel_Call {
	_c.Call.Return(readWriteCloser, err)
	return _c
}

func (_c *MockClient_OpenPortForwardTunnel_Call) RunAndReturn(run func(ctx context.Context, appID string, envName string, opts client.PortForwardTunnelOptions) (io.ReadWriteCloser, error)) *MockClient_OpenPortForwardTunnel_Call {
	_c.Call.Return(run)
	return _c
}

// RollbackAppConfigFileVersion provides a mock function for the type MockClient
func (_mock *MockClient) RollbackAppConfigFileVersion(ctx context.Context, appID string, versionID string, opts client.RollbackAppConfigFileVersionOptions) (*client.AppConfigFile, error) {
	ret := _mock.Called(ctx, appID, versionID, opts)

	if len(ret) == 0 {
		panic("no return value specified for RollbackAppConfigFileVersion")
	}

	var r0 *client.AppConfigFile
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, client.RollbackAppConfigFileVersionOptions) (*client.AppConfigFile, error)); ok {
		return returnFunc(ctx, appID, versionID, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, client.RollbackAppConfigFileVersionOptions) *client.AppConfigFile); ok {
		r0 = returnFunc(ctx, appID, versionID, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.AppConfigFile)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, client.RollbackAppConfigFileVersionOptions) error); ok {
		r1 = returnFunc(ctx, appID, versionID, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_RollbackAppConfigFileVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RollbackAppConfigFileVersion'
type MockClient_RollbackAppConfigFileVersion_Call struct {
	*mock.Call
}

// RollbackAppConfigFileVersion is a helper method to define mock.On call
//   - ctx context.Context
//   - appID string
//   - versionID string
//   - opts client.RollbackAppConfigFileVersionOptions
func (_e *MockClient_Expecter) RollbackAppConfigFileVersion(ctx any, appID any, versionID any, opts any) *MockClient_RollbackAppConfigFileVersion_Call {
	return &MockClient_RollbackAppConfigFileVersion_Call{Call: _e.mock.On("RollbackAppConfigFileVersion", ctx, appID, versionID, opts)}
}

func (_c *MockClient_RollbackAppConfigFileVersion_Call) Run(run func(ctx context.Context, appID string, versionID string, opts client.RollbackAppConfigFileVersionOptions)) *MockClient_RollbackAppConfigFileVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 client.RollbackAppConfigFileVersionOptions
		if args[3] != nil {
			arg3 = args[3].(client.RollbackAppConfigFileVersionOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockClient_RollbackAppConfigFileVersion_Call) Return(appConfigFile *client.AppConfigFile, err error) *MockClient_RollbackAppConfigFileVersion_Call {
	_c.Call.Return(appConfigFile, err)
	return _c
}

func (_c *MockClient_RollbackAppConfigFileVersion_Call) RunAndReturn(run func(ctx context.Context, appID string, versionID string, opts client.RollbackAppConfigFileVersionOptions) (*client.AppConfigFile, error)) *MockClient_RollbackAppConfigFileVersion_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateAppConfigFileContent provides a mock function for the type MockClient
func (_mock *MockClient) UpdateAppConfigFileContent(ctx context.Context, appID string, fileID string, opts client.AppConfigFileContentOptions) (*client.AppConfigFileContentUpdateResult, error) {
	ret := _mock.Called(ctx, appID, fileID, opts)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAppConfigFileContent")
	}

	var r0 *client.AppConfigFileContentUpdateResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, client.AppConfigFileContentOptions) (*client.AppConfigFileContentUpdateResult, error)); ok {
		return returnFunc(ctx, appID, fileID, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, client.AppConfigFileContentOptions) *client.AppConfigFileContentUpdateResult); ok {
		r0 = returnFunc(ctx, appID, fileID, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.AppConfigFileContentUpdateResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, client.AppConfigFileContentOptions) error); ok {
		r1 = returnFunc(ctx, appID, fileID, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_UpdateAppConfigFileContent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAppConfigFileContent'
type MockClient_UpdateAppConfigFileContent_Call struct {
	*mock.Call
}

// UpdateAppConfigFileContent is a helper method to define mock.On call
//   - ctx context.Context
//   - appID string
//   - fileID string
//   - opts client.AppConfigFileContentOptions
func (_e *MockClient_Expecter) UpdateAppConfigFileContent(ctx any, appID any, fileID any, opts any) *MockClient_UpdateAppConfigFileContent_Call {
	return &MockClient_UpdateAppConfigFileContent_Call{Call: _e.mock.On("UpdateAppConfigFileContent", ctx, appID, fileID, opts)}
}

func (_c *MockClient_UpdateAppConfigFileContent_Call) Run(run func(ctx context.Context, appID string, fileID string, opts client.AppConfigFileContentOptions)) *MockClient_UpdateAppConfigFileContent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 client.AppConfigFileContentOptions
		if args[3] != nil {
			arg3 = args[3].(client.AppConfigFileContentOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockClient_UpdateAppConfigFileContent_Call) Return(appConfigFileContentUpdateResult *client.AppConfigFileContentUpdateResult, err error) *MockClient_UpdateAppConfigFileContent_Call {
	_c.Call.Return(appConfigFileContentUpdateResult, err)
	return _c
}

func (_c *MockClient_UpdateAppConfigFileContent_Call) RunAndReturn(run func(ctx context.Context, appID string, fileID string, opts client.AppConfigFileContentOptions) (*client.AppConfigFileContentUpdateResult, error)) *MockClient_UpdateAppConfigFileContent_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateAppConfigFileOverlayContent provides a mock function for the type MockClient
func (_mock *MockClient) UpdateAppConfigFileOverlayContent(ctx context.Context, appID string, fileID string, opts client.AppConfigFileContentOptions) (*client.AppConfigFileContentUpdateResult, error) {
	ret := _mock.Called(ctx, appID, fileID, opts)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAppConfigFileOverlayContent")
	}

	var r0 *client.AppConfigFileContentUpdateResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, client.AppConfigFileContentOptions) (*client.AppConfigFileContentUpdateResult, error)); ok {
		return returnFunc(ctx, appID, fileID, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, client.AppConfigFileContentOptions) *client.AppConfigFileContentUpdateResult); ok {
		r0 = returnFunc(ctx, appID, fileID, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.AppConfigFileContentUpdateResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, client.AppConfigFileContentOptions) error); ok {
		r1 = returnFunc(ctx, appID, fileID, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_UpdateAppConfigFileOverlayContent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAppConfigFileOverlayContent'
type MockClient_UpdateAppConfigFileOverlayContent_Call struct {
	*mock.Call
}

// UpdateAppConfigFileOverlayContent is a helper method to define mock.On call
//   - ctx context.Context
//   - appID string
//   - fileID string
//   - opts client.AppConfigFileContentOptions
func (_e *MockClient_Expecter) UpdateAppConfigFileOverlayContent(ctx any, appID any, fileID any, opts any) *MockClient_UpdateAppConfigFileOverlayContent_Call {
	return &MockClient_UpdateAppConfigFileOverlayContent_Call{Call: _e.mock.On("UpdateAppConfigFileOverlayContent", ctx, appID, fileID, opts)}
}

func (_c *MockClient_UpdateAppConfigFileOverlayContent_Call) Run(run func(ctx context.Context, appID string, fileID string, opts client.AppConfigFileContentOptions)) *MockClient_UpdateAppConfigFileOverlayContent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 client.AppConfigFileContentOptions
		if args[3] != nil {
			arg3 = args[3].(client.AppConfigFileContentOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockClient_UpdateAppConfigFileOverlayContent_Call) Return(appConfigFileContentUpdateResult *client.AppConfigFileContentUpdateResult, err error) *MockClient_UpdateAppConfigFileOverlayContent_Call {
	_c.Call.Return(appConfigFileContentUpdateResult, err)
	return _c
}

func (_c *MockClient_UpdateAppConfigFileOverlayContent_Call) RunAndReturn(run func(ctx context.Context, appID string, fileID string, opts client.AppConfigFileContentOptions) (*client.AppConfigFileContentUpdateResult, error)) *MockClient_UpdateAppConfigFileOverlayContent_Call {
	_c.Call.Return(run)
	return _c
}

// ListAppPolarisConfigs provides a mock function for the type MockClient
func (_mock *MockClient) ListAppPolarisConfigs(ctx context.Context, appID string) ([]client.PolarisConfig, error) {
	ret := _mock.Called(ctx, appID)

	if len(ret) == 0 {
		panic("no return value specified for ListAppPolarisConfigs")
	}

	var r0 []client.PolarisConfig
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]client.PolarisConfig, error)); ok {
		return returnFunc(ctx, appID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []client.PolarisConfig); ok {
		r0 = returnFunc(ctx, appID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]client.PolarisConfig)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, appID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_ListAppPolarisConfigs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAppPolarisConfigs'
type MockClient_ListAppPolarisConfigs_Call struct {
	*mock.Call
}

// ListAppPolarisConfigs is a helper method to define mock.On call
//   - ctx context.Context
//   - appID string
func (_e *MockClient_Expecter) ListAppPolarisConfigs(ctx interface{}, appID interface{}) *MockClient_ListAppPolarisConfigs_Call {
	return &MockClient_ListAppPolarisConfigs_Call{Call: _e.mock.On("ListAppPolarisConfigs", ctx, appID)}
}

func (_c *MockClient_ListAppPolarisConfigs_Call) Run(run func(ctx context.Context, appID string)) *MockClient_ListAppPolarisConfigs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_ListAppPolarisConfigs_Call) Return(polarisConfigs []client.PolarisConfig, err error) *MockClient_ListAppPolarisConfigs_Call {
	_c.Call.Return(polarisConfigs, err)
	return _c
}

func (_c *MockClient_ListAppPolarisConfigs_Call) RunAndReturn(run func(ctx context.Context, appID string) ([]client.PolarisConfig, error)) *MockClient_ListAppPolarisConfigs_Call {
	_c.Call.Return(run)
	return _c
}

// CreateAppPolarisConfig provides a mock function for the type MockClient
func (_mock *MockClient) CreateAppPolarisConfig(ctx context.Context, appID string, body any) (string, error) {
	ret := _mock.Called(ctx, appID, body)

	if len(ret) == 0 {
		panic("no return value specified for CreateAppPolarisConfig")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, any) (string, error)); ok {
		return returnFunc(ctx, appID, body)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, any) string); ok {
		r0 = returnFunc(ctx, appID, body)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, any) error); ok {
		r1 = returnFunc(ctx, appID, body)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_CreateAppPolarisConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAppPolarisConfig'
type MockClient_CreateAppPolarisConfig_Call struct {
	*mock.Call
}

// CreateAppPolarisConfig is a helper method to define mock.On call
//   - ctx context.Context
//   - appID string
//   - body any
func (_e *MockClient_Expecter) CreateAppPolarisConfig(ctx interface{}, appID interface{}, body interface{}) *MockClient_CreateAppPolarisConfig_Call {
	return &MockClient_CreateAppPolarisConfig_Call{Call: _e.mock.On("CreateAppPolarisConfig", ctx, appID, body)}
}

func (_c *MockClient_CreateAppPolarisConfig_Call) Run(run func(ctx context.Context, appID string, body any)) *MockClient_CreateAppPolarisConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2]
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_CreateAppPolarisConfig_Call) Return(name string, err error) *MockClient_CreateAppPolarisConfig_Call {
	_c.Call.Return(name, err)
	return _c
}

func (_c *MockClient_CreateAppPolarisConfig_Call) RunAndReturn(run func(ctx context.Context, appID string, body any) (string, error)) *MockClient_CreateAppPolarisConfig_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAppPolarisConfig provides a mock function for the type MockClient
func (_mock *MockClient) DeleteAppPolarisConfig(ctx context.Context, appID string, configName string) error {
	ret := _mock.Called(ctx, appID, configName)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAppPolarisConfig")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, appID, configName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_DeleteAppPolarisConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAppPolarisConfig'
type MockClient_DeleteAppPolarisConfig_Call struct {
	*mock.Call
}

// DeleteAppPolarisConfig is a helper method to define mock.On call
//   - ctx context.Context
//   - appID string
//   - configName string
func (_e *MockClient_Expecter) DeleteAppPolarisConfig(ctx interface{}, appID interface{}, configName interface{}) *MockClient_DeleteAppPolarisConfig_Call {
	return &MockClient_DeleteAppPolarisConfig_Call{Call: _e.mock.On("DeleteAppPolarisConfig", ctx, appID, configName)}
}

func (_c *MockClient_DeleteAppPolarisConfig_Call) Run(run func(ctx context.Context, appID string, configName string)) *MockClient_DeleteAppPolarisConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_DeleteAppPolarisConfig_Call) Return(err error) *MockClient_DeleteAppPolarisConfig_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_DeleteAppPolarisConfig_Call) RunAndReturn(run func(ctx context.Context, appID string, configName string) error) *MockClient_DeleteAppPolarisConfig_Call {
	_c.Call.Return(run)
	return _c
}

// PatchAppPolarisConfig provides a mock function for the type MockClient
func (_mock *MockClient) PatchAppPolarisConfig(ctx context.Context, appID string, configName string, body any) error {
	ret := _mock.Called(ctx, appID, configName, body)

	if len(ret) == 0 {
		panic("no return value specified for PatchAppPolarisConfig")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, any) error); ok {
		r0 = returnFunc(ctx, appID, configName, body)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_PatchAppPolarisConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PatchAppPolarisConfig'
type MockClient_PatchAppPolarisConfig_Call struct {
	*mock.Call
}

// PatchAppPolarisConfig is a helper method to define mock.On call
//   - ctx context.Context
//   - appID string
//   - configName string
//   - body any
func (_e *MockClient_Expecter) PatchAppPolarisConfig(ctx interface{}, appID interface{}, configName interface{}, body interface{}) *MockClient_PatchAppPolarisConfig_Call {
	return &MockClient_PatchAppPolarisConfig_Call{Call: _e.mock.On("PatchAppPolarisConfig", ctx, appID, configName, body)}
}

func (_c *MockClient_PatchAppPolarisConfig_Call) Run(run func(ctx context.Context, appID string, configName string, body any)) *MockClient_PatchAppPolarisConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 any
		if args[3] != nil {
			arg3 = args[3]
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockClient_PatchAppPolarisConfig_Call) Return(err error) *MockClient_PatchAppPolarisConfig_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_PatchAppPolarisConfig_Call) RunAndReturn(run func(ctx context.Context, appID string, configName string, body any) error) *MockClient_PatchAppPolarisConfig_Call {
	_c.Call.Return(run)
	return _c
}

// --- AppSpec mock methods ---

func (_mock *MockClient) GetAppDetail(ctx context.Context, appID string) (*client.AppDetail, error) {
	ret := _mock.Called(ctx, appID)
	var r0 *client.AppDetail
	if ret.Get(0) != nil {
		r0 = ret.Get(0).(*client.AppDetail)
	}
	return r0, ret.Error(1)
}

func (_mock *MockClient) GetAppSpecDefaultSection(ctx context.Context, appID string, section client.AppSpecSectionName, result any) error {
	ret := _mock.Called(ctx, appID, section, result)
	return ret.Error(0)
}

func (_mock *MockClient) GetAppSpecEnvEffectiveSection(ctx context.Context, appID string, envName string, section client.AppSpecSectionName, result any) error {
	ret := _mock.Called(ctx, appID, envName, section, result)
	return ret.Error(0)
}

func (_mock *MockClient) SetAppSpecDefaultSection(ctx context.Context, appID string, section client.AppSpecSectionName, body any) error {
	ret := _mock.Called(ctx, appID, section, body)
	return ret.Error(0)
}

func (_mock *MockClient) SetAppSpecEnvSection(ctx context.Context, appID string, envName string, section client.AppSpecSectionName, body any) error {
	ret := _mock.Called(ctx, appID, envName, section, body)
	return ret.Error(0)
}

func (_mock *MockClient) DeleteAppSpecEnvSection(ctx context.Context, appID string, envName string, section client.AppSpecSectionName) error {
	ret := _mock.Called(ctx, appID, envName, section)
	return ret.Error(0)
}

func (_mock *MockClient) UpdateAppStartCommand(ctx context.Context, appID string, appType string, body any) error {
	ret := _mock.Called(ctx, appID, appType, body)
	return ret.Error(0)
}

// --- Auth mock methods ---

// ValidateAccessToken provides a mock function for the type MockClient
func (_mock *MockClient) ValidateAccessToken(accessToken string) (string, error) {
	ret := _mock.Called(accessToken)

	if len(ret) == 0 {
		panic("no return value specified for ValidateAccessToken")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(accessToken)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(accessToken)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ExchangeBkTicketForToken provides a mock function for the type MockClient
func (_mock *MockClient) ExchangeBkTicketForToken(username, bkTicket string) (string, error) {
	ret := _mock.Called(username, bkTicket)

	if len(ret) == 0 {
		panic("no return value specified for ExchangeBkTicketForToken")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = returnFunc(username, bkTicket)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(username, bkTicket)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}
